gapi.loaded_0(function(_){var window=this;
try{
_.l=function(a){throw a;};_.n=void 0;_.q=!0;_.r=null;_.t=!1;_.aa=function(){return function(a){return a}};_.w=function(){return function(){}};_.ba=function(a){return function(c){this[a]=c}};_.x=function(a){return function(){return this[a]}};_.y=function(a){return function(){return a}};
_.ca=function(a){var c=typeof a;if("object"==c)if(a){if(a instanceof window.Array)return"array";if(a instanceof window.Object)return c;var f=window.Object.prototype.toString.call(a);if("[object Window]"==f)return"object";if("[object Array]"==f||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==f||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof a.call)return"object";return c};_.D=function(a){return a!==_.n};_.da=function(a){return"array"==(0,_.ca)(a)};_.ea=function(a){var c=typeof a;return"object"==c&&a!=_.r||"function"==c};_.fa=function(a,c,f){return a.call.apply(a.bind,arguments)};
_.ga=function(a,c,f){a||(0,_.l)((0,window.Error)());if(2<arguments.length){var g=window.Array.prototype.slice.call(arguments,2);return function(){var f=window.Array.prototype.slice.call(arguments);window.Array.prototype.unshift.apply(f,g);return a.apply(c,f)}}return function(){return a.apply(c,arguments)}};_.E=function(a,c,f){_.E=window.Function.prototype.bind&&-1!=window.Function.prototype.bind.toString().indexOf("native code")?_.fa:_.ga;return _.E.apply(_.r,arguments)};
_.ha=function(a,c){var f=window.Array.prototype.slice.call(arguments,1);return function(){var c=window.Array.prototype.slice.call(arguments);c.unshift.apply(c,f);return a.apply(this,c)}};_.F=function(a,c){function f(){}f.prototype=c.prototype;a.p=c.prototype;a.prototype=new f;a.prototype.constructor=a};_._DumpException=function(a){(0,_.l)(a)};_.ia=_.ia||{};_.J=this;_.ja="closure_uid_"+window.Math.floor(2147483648*window.Math.random()).toString(36);_.ka=window.Date.now||function(){return+new window.Date}; window.Function.prototype.bind=window.Function.prototype.bind||function(a,c){if(1<arguments.length){var f=window.Array.prototype.slice.call(arguments,1);f.unshift(this,a);return _.E.apply(_.r,f)}return(0,_.E)(this,a)};
_.la=window.gapi||{};_.ma=window.gadgets||{};_.L=window.osapi=window.osapi||{};
}catch(e){_._DumpException(e)}
try{
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{jsonpOverride:_.t},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.t},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.t},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/u/:session_index:/_/pages/badge"},":socialhost:":"https://plusone.google.com",card:{params:{s:"#",userid:"&"},url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton"},
plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator"}},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"chili.people.list":_.q,"pos.plusones.list":_.q,"pos.plusones.get":_.q,"chili.people.get":_.q,"pos.plusones.insert":_.q,"chili.activities.list":_.q,"pos.plusones.delete":_.q,"chili.activities.get":_.q,"chili.activities.search":_.q,"pos.plusones.getSignupState":_.q},
requestCache:{enabled:_.q},versions:{chili:"v1",pos:"v1"},rpc:"/rpc",root:"https://www.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:_.q},transport:{isProxyShared:_.q},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:_.t}}});

window.___jsl=window.___jsl||{};(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"onload"},iframes:{card:{url:":socialhost:/u/:session_index:/_/hovercard/card"}}});

}catch(e){_._DumpException(e)}
try{
_.M=function(a,c,f){a=a.split(".");f=f||_.J;!(a[0]in f)&&f.execScript&&f.execScript("var "+a[0]);for(var g;a.length&&(g=a.shift());)!a.length&&(0,_.D)(c)?f[g]=c:f=f[g]?f[g]:f[g]={}};_.na=function(a,c,f){return a[c]=a[c]||f};_.oa=function(a){for(var c=0;c<this.length;c++)if(this[c]===a)return c;return-1};_.pa=function(){var a;if((a=window.Object.create)&&_.sa.test(a))a=a(_.r);else{a={};for(var c in a)a[c]=_.n}return a};_.ta=function(){return window.___jsl=window.___jsl||{}};
_.ua=function(a){var c=(0,_.ta)();c[a]=c[a]||[];return c[a]};_.va=function(a){var c=(0,_.ta)();c.cfg=!a&&c.cfg||{};return c.cfg};_.wa=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};_.xa=function(a,c){if(c)for(var f in c)c.hasOwnProperty(f)&&(a[f]&&c[f]&&"object"===typeof a[f]&&"object"===typeof c[f]&&!(0,_.wa)(a[f])&&!(0,_.wa)(c[f])?(0,_.xa)(a[f],c[f]):c[f]&&"object"===typeof c[f]?(a[f]=(0,_.wa)(c[f])?[]:{},(0,_.xa)(a[f],c[f])):a[f]=c[f])};
_.ya=function(a){(0,_.va)(_.q);var c=window.___gcfg,f=(0,_.ua)("cu");if(c&&c!==window.___gu){var g={};(0,_.xa)(g,c);f.push(g);window.___gu=c}var c=(0,_.ua)("cu"),h=window.document.scripts||window.document.getElementsByTagName("script")||[],g=[],k=[],m=(0,_.ta)().u;m&&k.push(m);(0,_.ta)().us&&k.push.apply(k,(0,_.ta)().us);for(m=0;m<h.length;++m)for(var p=h[m],s=0;s<k.length;++s)p.src&&0==p.src.indexOf(k[s])&&g.push(p);0==g.length&&h[h.length-1].src&&g.push(h[h.length-1]);for(h=0;h<g.length;++h)if(!g[h].getAttribute("gapi_processed")){g[h].setAttribute("gapi_processed",
_.q);(k=g[h])?(m=k.nodeType,k=3==m||4==m?k.nodeValue:k.textContent||k.innerText||k.innerHTML||""):k=_.n;if(k){for(;0==k.charCodeAt(k.length-1);)k=k.substring(0,k.length-1);m=_.n;try{m=(new window.Function("return ("+k+"\n)"))()}catch(u){}if("object"===typeof m)k=m;else{try{m=(new window.Function("return ({"+k+"\n})"))()}catch(v){}k="object"===typeof m?m:{}}}else k=_.n;k&&c.push(k)}a&&(g={},(0,_.xa)(g,a),f.push(g));g=(0,_.ua)("cd");a=0;for(c=g.length;a<c;++a)(0,_.xa)((0,_.va)(),g[a]);g=(0,_.ua)("ci");
a=0;for(c=g.length;a<c;++a)(0,_.xa)((0,_.va)(),g[a]);a=0;for(c=f.length;a<c;++a)(0,_.xa)((0,_.va)(),f[a])};_.N=function(a,c){if(!a)return(0,_.va)();for(var f=a.split("/"),g=(0,_.va)(),h=0,k=f.length;g&&"object"===typeof g&&h<k;++h)g=g[f[h]];return h===f.length&&g!==_.n?g:c};_.za=function(a,c){var f=a;if("string"===typeof a){for(var g=f={},h=a.split("/"),k=0,m=h.length;k<m-1;++k)var p={},g=g[h[k]]=p;g[h[k]]=c}(0,_.ya)(f)};_.O=function(a,c){c="function"==typeof _.Aa&&(0,_.Aa)(a,c)||c;(0,_.M)(a,c,_.n)};
_.Ca=window;_.Da=window.document;_.sa=/\[native code\]/;(0,_.na)(_.Ca,"gapi",{});_.Ea=(0,_.na)(_.Ca,"___jsl",(0,_.pa)());(0,_.na)(_.Ea,"I",0);(0,_.na)(_.Ea,"hel",10);_.Fa=window.__GOOGLEAPIS;_.Fa&&(_.Fa.googleapis&&!_.Fa["googleapis.config"]&&(_.Fa["googleapis.config"]=_.Fa.googleapis),(0,_.na)(_.Ea,"ci",[]).push(_.Fa),window.__GOOGLEAPIS=_.n);(0,_.ya)();(0,_.O)("gapi.config.get",_.N);(0,_.O)("gapi.config.update",_.za);

}catch(e){_._DumpException(e)}
try{


}catch(e){_._DumpException(e)}
try{


}catch(e){_._DumpException(e)}
try{
_.Na={go:{},O:{}};_.Oa={go:{},O:{}};

}catch(e){_._DumpException(e)}
try{


}catch(e){_._DumpException(e)}
try{
_.Q=_.Q||{};

}catch(e){_._DumpException(e)}
try{
_.Q=_.Q||{};_.Q.yd=function(a,c,f){for(var g=[],h=2,k=arguments.length;h<k;++h)g.push(arguments[h]);return function(){for(var f=g.slice(),h=0,k=arguments.length;h<k;++h)f.push(arguments[h]);return c.apply(a,f)}};_.Q.se=function(a){var c,f,g={};for(c=0;f=a[c];++c)g[f]=f;return g};


}catch(e){_._DumpException(e)}
try{
_.Va=function(a,c){return window.String.fromCharCode(c)};_.Q=_.Q||{};_.Wa={"0":_.t,10:_.q,13:_.q,34:_.q,39:_.q,60:_.q,62:_.q,92:_.q,8232:_.q,8233:_.q,65282:_.q,65287:_.q,65308:_.q,65310:_.q,65340:_.q};_.Q.escape=function(a,c){if(a){if("string"===typeof a)return _.Q.Yd(a);if("array"===typeof a)for(var f=0,g=a.length;f<g;++f)a[f]=_.Q.escape(a[f]);else if("object"===typeof a&&c){f={};for(g in a)a.hasOwnProperty(g)&&(f[_.Q.Yd(g)]=_.Q.escape(a[g],_.q));return f}}return a}; _.Q.Yd=function(a){if(!a)return a;for(var c=[],f,g,h=0,k=a.length;h<k;++h)f=a.charCodeAt(h),g=_.Wa[f],g===_.q?c.push("&#",f,";"):g!==_.t&&c.push(a.charAt(h));return c.join("")};_.Q.Kq=function(a){return!a?a:a.replace(/&#([0-9]+);/g,_.Va)};


}catch(e){_._DumpException(e)}
try{
_.Ya=_.Ya||{};_.Ya.Zm=function(){var a=0,c=0;window.self.innerHeight?(a=window.self.innerWidth,c=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,c=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,c=window.document.body.clientHeight);return{width:a,height:c}};


}catch(e){_._DumpException(e)}
try{
_.Za=function(a,c){window.getComputedStyle(a,"").getPropertyValue(c).match(/^([0-9]+)/);return(0,window.parseInt)(window.RegExp.$1,10)};_.Ya=_.Ya||{};
_.Ya.yg=function(){var a=_.Ya.Zm().height,c=window.document.body,f=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&f.scrollHeight)return f.scrollHeight!==a?f.scrollHeight:f.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){a=0;for(c=[window.document.body];0<c.length;){var g=c.shift(),f=g.childNodes;if("undefined"!==typeof g.style){var h=g.style.overflowY;h||(h=(h=window.document.defaultView.getComputedStyle(g,_.r))?h.overflowY:_.r);if("visible"!=h&&
"inherit"!=h&&(h=g.style.height,h||(h=(h=window.document.defaultView.getComputedStyle(g,_.r))?h.height:""),0<h.length&&"auto"!=h))continue}for(g=0;g<f.length;g++){h=f[g];if("undefined"!==typeof h.offsetTop&&"undefined"!==typeof h.offsetHeight)var k=h.offsetTop+h.offsetHeight+(0,_.Za)(h,"margin-bottom"),a=window.Math.max(a,k);c.push(h)}}return a+(0,_.Za)(window.document.body,"border-bottom")+(0,_.Za)(window.document.body,"margin-bottom")+(0,_.Za)(window.document.body,"padding-bottom")}if(c&&f)return g= f.scrollHeight,h=f.offsetHeight,f.clientHeight!==h&&(g=c.scrollHeight,h=c.offsetHeight),g>a?g>h?g:h:g<h?g:h};


}catch(e){_._DumpException(e)}
try{
_.Ra=function(a,c){if(!(a<_.Sa)&&_._console$$inline_228)if(2===a&&_._console$$inline_228.warn)_._console$$inline_228.warn(c);else if(3===a&&_._console$$inline_228.error)try{_._console$$inline_228.error(c)}catch(f){}else _._console$$inline_228.log&&_._console$$inline_228.log(c)};_.Ta=function(a){(0,_.Ra)(1,a)};
_.Ua=function(a){(0,_.Ra)(2,a)};_.Ma=function(a){(0,_.Ra)(3,a)};_.Ta.INFO=1;_.Ta.WARNING=2;_.Ta.NONE=4;_.Sa=1;_._console$$inline_228=window.console?window.console:window.opera?window.opera.postError:_.n;

}catch(e){_._DumpException(e)}
try{
_.Q=_.Q||{};_.Q.Sd=function(a,c,f,g){"undefined"!=typeof a.addEventListener?a.addEventListener(c,f,g):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+c,f):(0,_.Ua)("cannot attachBrowserEvent: "+c)};_.Q.Ao=function(a,c,f,g){a.removeEventListener?a.removeEventListener(c,f,g):a.detachEvent?a.detachEvent("on"+c,f):(0,_.Ua)("cannot removeBrowserEvent: "+c)};


}catch(e){_._DumpException(e)}
try{
_.$a=function(){function a(){h[0]=1732584193;h[1]=4023233417;h[2]=2562383102;h[3]=271733878;h[4]=3285377520;v=u=0}function c(a){for(var c=m,f=0;64>f;f+=4)c[f/4]=a[f]<<24|a[f+1]<<16|a[f+2]<<8|a[f+3];for(f=16;80>f;f++)c[f]=((c[f-3]^c[f-8]^c[f-14]^c[f-16])<<1|(c[f-3]^c[f-8]^c[f-14]^c[f-16])>>>31)&4294967295;for(var a=h[0],g=h[1],k=h[2],p=h[3],s=h[4],v,u,f=0;80>f;f++)40>f?20>f?(v=p^g&(k^p),u=1518500249):(v=g^k^p,u=1859775393):60>f?(v=g&k|p&(g|k),u=2400959708):(v=g^k^p,u=3395469782),v=((a<<5|a>>>27)&4294967295)+
v+s+u+c[f]&4294967295,s=p,p=k,k=(g<<30|g>>>2)&4294967295,g=a,a=v;h[0]=h[0]+a&4294967295;h[1]=h[1]+g&4294967295;h[2]=h[2]+k&4294967295;h[3]=h[3]+p&4294967295;h[4]=h[4]+s&4294967295}function f(a,f){if("string"===typeof a){for(var a=(0,window.unescape)((0,window.encodeURIComponent)(a)),g=[],h=0,m=a.length;h<m;++h)g.push(a.charCodeAt(h));a=g}f||(f=a.length);g=0;if(0==u)for(;g+64<f;)c(a.slice(g,g+64)),g+=64,v+=64;for(;g<f;)if(k[u++]=a[g++],v++,64==u){u=0;for(c(k);g+64<f;)c(a.slice(g,g+64)),g+=64,v+=64}}
function g(){var a=[],g=8*v;56>u?f(p,56-u):f(p,64-(u-56));for(var m=63;56<=m;m--)k[m]=g&255,g>>>=8;c(k);for(m=g=0;5>m;m++)for(var s=24;0<=s;s-=8)a[g++]=h[m]>>s&255;return a}for(var h=[],k=[],m=[],p=[128],s=1;64>s;++s)p[s]=0;var u,v;a();return{reset:a,update:f,hq:g,Me:function(){for(var a=g(),c="",f=0;f<a.length;f++)c+="0123456789ABCDEF".charAt(window.Math.floor(a[f]/16))+"0123456789ABCDEF".charAt(a[f]%16);return c}}};


}catch(e){_._DumpException(e)}
try{
_.bb=function(a){var c=(0,_.$a)();c.update(a);return c.Me()};_.cb=window.crypto;
if(_.cb&&"function"==typeof _.cb.getRandomValues)_.ab=function(){var a=new window.Uint32Array(1);_.cb.getRandomValues(a);return(0,window.Number)("0."+a[0])};else{_.fb=(0,_.N)("random/maxObserveMousemove");_.fb==_.r&&(_.fb=-1);_.gb=0;_.ib=window.Math.random();_.jb=1;_.kb=1E6*(window.screen.width*window.screen.width+window.screen.height);_.lb=function(a){var a=a||window.event,c=a.screenX+a.clientX<<16,c=c+(a.screenY+a.clientY),c=c*((new window.Date).getTime()%1E6);_.jb=_.jb*c%_.kb;0<_.fb&&++_.gb==_.fb&&
_.Q.Ao(window,"mousemove",_.lb,_.t)};0!=_.fb&&_.Q.Sd(window,"mousemove",_.lb,_.t);_.mb=(0,_.bb)(window.document.cookie+"|"+window.document.location+"|"+(new window.Date).getTime()+"|"+_.ib);_.ab=function(){var a=_.jb,a=a+(0,window.parseInt)(_.mb.substr(0,20),16);_.mb=(0,_.bb)(_.mb);return a/(_.kb+window.Math.pow(16,20))}};
(0,_.O)("shindig.random",_.ab);

}catch(e){_._DumpException(e)}
try{
_.Q=_.Q||{};_.nb=[];_.Q.xq=function(a){_.nb.push(a)};_.Q.Dq=function(){for(var a=0,c=_.nb.length;a<c;++a)_.nb[a]()};

}catch(e){_._DumpException(e)}
try{
_.ob=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;_.ob&&(0,_.za)((0,_.ob)());_.R={N:function(a,c,f){f&&f((0,_.N)())},get:function(a){return(0,_.N)(a)},update:function(a,c){c&&(0,_.l)("Config replacement is not supported");(0,_.za)(a)},S:(0,_.w)()};
(0,_.O)("gadgets.config.register",_.R.N);(0,_.O)("gadgets.config.get",_.R.get);(0,_.O)("gadgets.config.init",_.R.S);(0,_.O)("gadgets.config.update",_.R.update);

}catch(e){_._DumpException(e)}
try{
if(window.JSON&&window.JSON.parse&&window.JSON.stringify){_.Pa=function(a){return this[a]};_.Qa=/___$/;_.P={parse:function(a){try{return window.JSON.parse(a)}catch(c){return _.t}},stringify:function(a){function c(a){return f.call(this,a,_.Pa)}var f=window.JSON.stringify,g=window.Array.prototype.toJSON&&'"[{\\"x\\": 1}]"'===f([{x:1}])?c:f;try{return g(a,function(a,c){return!_.Qa.test(a)?c:_.n})}catch(h){return _.r}}}};
if(!window.JSON||!window.JSON.parse||!window.JSON.stringify)_.P=function(){function a(a){return 10>a?"0"+a:a}function c(a){var h,k,m;h=/[\"\\\x00-\x1f\x7f-\x9f]/g;switch(typeof a){case "string":return h.test(a)?'"'+a.replace(h,function(a){var c=f[a];if(c)return c;c=a.charCodeAt();return"\\u00"+window.Math.floor(c/16).toString(16)+(c%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?(0,window.String)(a):"null";case "boolean":case "null":return(0,window.String)(a);case "object":if(!a)return"null";
h=[];if("number"===typeof a.length&&!a.propertyIsEnumerable("length")){m=a.length;for(k=0;k<m;k+=1)h.push(c(a[k])||"null");return"["+h.join(",")+"]"}for(k in a)!/___$/.test(k)&&a.hasOwnProperty(k)&&"string"===typeof k&&(m=c(a[k]))&&h.push(c(k)+":"+m);return"{"+h.join(",")+"}"}return""}window.Date.prototype.toJSON=function(){return[this.getUTCFullYear(),"-",a(this.getUTCMonth()+1),"-",a(this.getUTCDate()),"T",a(this.getUTCHours()),":",a(this.getUTCMinutes()),":",a(this.getUTCSeconds()),"Z"].join("")};
var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return{stringify:c,parse:function(a){return/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))?eval("("+a+")"):_.t}}}();
_.P.zi=function(a){var c={};if(a===_.r||a===_.n)return c;for(var f in a)if(a.hasOwnProperty(f)){var g=a[f];_.r===g||_.n===g||(c[f]="string"===typeof g?g:_.P.stringify(g))}return c};(0,_.O)("gadgets.json.flatten",_.P.zi);(0,_.O)("gadgets.json.parse",_.P.parse);(0,_.O)("gadgets.json.stringify",_.P.stringify);(0,_.O)("gadgets.json.flatten",_.P.zi);(0,_.O)("gadgets.json.parse",_.P.parse);(0,_.O)("gadgets.json.stringify",_.P.stringify);


}catch(e){_._DumpException(e)}
try{
_.Q=_.Q||{};_.Xa=_.r;
_.Q.X=function(a){var c="undefined"===typeof a;if(_.Xa!==_.r&&c)return _.Xa;for(var f={},a=a||window.document.location.href,g=a.indexOf("?"),h=a.indexOf("#"),a=(-1===h?a.substr(g+1):[a.substr(g+1,h-g-1),"&",a.substr(h+1)].join("")).split("&"),g=window.decodeURIComponent?window.decodeURIComponent:window.unescape,h=0,k=a.length;h<k;++h){var m=a[h].indexOf("=");if(-1!==m){var p=a[h].substring(0,m),m=a[h].substring(m+1),m=m.replace(/\+/g," ");try{f[p]=g(m)}catch(s){}}}c&&(_.Xa=f);return f};_.Q.X();
(0,_.O)("gadgets.util.getUrlParameters",_.Q.X);

}catch(e){_._DumpException(e)}
try{
_.pb=window.gapi&&window.gapi.util||{};

}catch(e){_._DumpException(e)}
try{
_.pb.na=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^\w*:\/\//.test(a)||(a=window.location.href);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));var a=a.substring(0,a.indexOf("://")),f="",g=c.indexOf(":");if(-1!=g){var h=c.substring(g+1),c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f};


}catch(e){_._DumpException(e)}
try{
if(window.gapi&&window.gapi.rpc){_.rb=window.gapi.rpc;_.rb.call=_.rb.call;_.rb.N=_.rb.register;_.rb.Xb=_.rb.unregister;_.rb.xc=_.rb.setup;_.rb.dp=_.rb.sw;_.qb=_.rb}else{_.tb=function(a){if(a.f in{})return _.t;var c=a.t,f=_.sb[a.r],a=a.origin;return f&&(f.Ld===c||!f.Ld&&!c)&&(a===f.origin||"*"===f.origin)};_.yb=function(a,c,f){a=(0,_.ub)(a);_.wb[a.name]={ym:c,qe:a.qe,mp:f||_.tb};(0,_.xb)()};_.Bb=function(a){var c=a.c;if(!c)return(0,_.w)();var f=a.r,g=a.g?"legacy__":"";return function(){var a=[].slice.call(arguments,
0);_.zb?a.unshift(f,g+"__cb",_.r,c):a.unshift(f,g+"__cb"+c,_.r);_.Ab.apply(_.r,a)}};_.Ib=function(a,c,f,g){var h=_.Cb,k=_.Db,m=_.sb[c],p=h,s=(0,_.Eb)(c);if(m&&".."!==c){if(s.bh){if(!(k=_.sb[c].Go)){k=_.r;k=_.Fb?_.Fb.substring(1).split("/"):[_.Cb];p=k.length-1;for(c=window.parent;c!==window.top;){var u=c.parent;if(!p--){for(var v=_.r,A=u.frames.length,B=0;B<A;++B)u.frames[B]==c&&(v=B);k.unshift("{"+v+"}")}c=u}k="/"+k.join("/")}p=k}else p=h="..";k=m.Ld}m=p;if(g&&s){p=_.tb;if(s.bh)var p=s.id.split("/"),
H=p[p.length-1],I=s.origin,p=function(a){var c=a.origin;return a.f==H&&(I==c||"*"==I)};_.zb?_.Gb["_"+ ++_.Hb]=[g,p]:(0,_.yb)("__cb"+(0,window.String)(++_.Hb),g,p);g=_.Hb}else g=_.r;f={s:a,f:h,r:m,t:k,c:g,a:f};a=(0,_.ub)(a);f.s=a.name;f.g=a.qe;return f};_.Lb=function(a){var c=_.sb[a];if(c&&c.zb){var f=c.Bh;c.Bh=[];if(_.Jb)f.length&&(f=(0,_.Ib)("_processBatch",a,[f]),_.Kb.send(a,_.P.stringify(f),c.origin));else for(;f.length;)_.Kb.send(a,_.P.stringify(f.shift()),c.origin)}};_.ub=function(a){return 0===
a.indexOf("legacy__")?{name:a.substring(8),qe:_.q}:{name:a,qe:_.t}};_.xb=function(){for(var a=0,c;c=_.Mb[a];++a){var f=c.Jd,g=f.s,h=_.wb[g]||_.wb["*"];if(h&&(_.Mb.splice(a,1),--a,f.origin=c.origin,c=(0,_.Bb)(f),f.callback=c,h.mp(f))){if("__cb"!==g&&!!h.qe!=!!f.g)break;f=h.ym.apply(f,f.a);f!==_.n&&c(f)}}};_.Eb=function(a){var c=_.t,a=a.split("|"),f=a[0];0<=f.indexOf("/")&&(c=_.q);return{id:f,origin:a[1]||"*",bh:c}};_.Pb=function(a,c){var f=(0,_.Eb)(a),a=f.id;if(!_.sb.hasOwnProperty(a)){var g=_.Db,
h=_.r;f.bh?(g=_.r,h=f.origin):".."!==a?(g=window.document.getElementById(a).src,h=_.pb.na(g),g=(0,_.Nb)(g).rpctoken):h=_.pb.na(_.Ob);f.origin&&(h=f.origin);_.sb[a]={Ld:g,Bh:[],origin:h,Go:c,Xj:function(){var c=a;_.sb[c].zb=1;(0,_.Lb)(c)}};_.Kb.xc(a,_.sb[a].Xj)}return _.sb[a].Xj};_.Qb=function(){return"function"===typeof window.postMessage||"object"===typeof window.postMessage};_.Ab=function(a,c,f,g){a=a||"..";(0,_.Pb)(a);var a=a.split("|",1)[0],h=[].slice.call(arguments,3),h=(0,_.Ib)(c,a,h,f);_.sb[a].Bh.push(h);
var k=a;_.Rb[k]||(_.Rb[k]=window.setTimeout(function(){_.Rb[k]=_.t;(0,_.Lb)(k)},0))};_.Sb={call:_.Ab,N:_.yb,Xb:function(a){delete _.wb[(0,_.ub)(a).name]},xc:_.Pb,dp:_.Qb};if((0,_.Qb)()){_.Jb=_.t;_.Hb=0;_.Mb=[];_.sb={};_.wb={};_.Nb=_.Q.X;_.Tb=(0,_.Nb)();_.Db=_.Tb.rpctoken;_.Ob=_.Tb.parent||window.document.referrer;_.Cb=window!==window.top&&window.name||"..";_.Fb=_.r;_.Rb={};_.Ub={rm:function(a,c){var f=_.P.parse(a);_.Mb.push({Jd:f,origin:c});(0,_.xb)()},$m:function(a){var c=window;"/"==a.charAt(0)&&
(a=a.substring(1),c=window.top);for(a=a.split("/");a.length;){var f;f=a.shift();"{"==f.charAt(0)&&"}"==f.charAt(f.length-1)&&(f=f.substring(1,f.length-1));if(".."===f)c=c.parent;else if(".."!==f&&c.frames[f])c=c.frames[f],"postMessage"in c||(0,_.l)("Not a window");else return _.r}return c},b:_.Cb,Fg:function(a){return(a=_.sb[a])&&a.Ld},d:function(a){_.Fb=a}};_.Vb=function(a){a=_.P.parse(a);return a!=_.r&&"object"===typeof a&&!!a.g};_.Xb=function(a){var c=(0,window.String)(a.data),f=0!==c.indexOf("!_");
f||(c=c.substring(2));var g=(0,_.Vb)(c);if(f==g){if(!g&&(f=_.r,0==c.indexOf("{h:'")&&c.indexOf("'}")==c.length-2&&(f=(0,window.unescape)(c.substring(4,c.length-2))),f)){if(_.Wb[f])_.Wb[f]();return}var h=a.origin;window.setTimeout(function(){_.Ub.rm(c,h)},0)}};_.Wb={};_.Yb=_.r;(_.Yb=window.addEventListener)?(0,_.Yb)("message",_.Xb,_.t):(_.Yb=window.attachEvent)&&(0,_.Yb)("onmessage",_.Xb);window.___jsl=window.___jsl||{};_.Zb=window.___jsl;_.Zb.RPMQ=_.Zb.RPMQ||[];_.Zb.RPMQ.push(_.Xb);if(window!==window.parent){_.$b=
window.parent;_.ac="{h:'"+(0,window.escape)(window.name)+"'}";_.bc=(0,_.Vb)(_.ac)?"":"!_";_.$b.postMessage(_.bc+_.ac,"*")}_.Kb={xc:function(a,c){".."==a?c():_.Wb[a]=c},send:function(a,c,f){var a=_.Ub.$m(a),g=(0,_.Vb)(c)?"":"!_";a.postMessage(g+c,f)}};_.Gb={};_.zb=_.q;(0,_.yb)("__cb",function(a,c){var f=_.Gb["_"+a];f&&f[1](this)&&f[0].call(this,c)},(0,_.y)(_.q));(0,_.yb)("_processBatch",function(a){for(;a.length;){var c=a.shift();_.Mb.push({Jd:c,origin:this.origin})}(0,_.xb)()},(0,_.y)(_.q));(0,_.Pb)("..")}_.qb= _.Sb}_.cc=_.qb;


}catch(e){_._DumpException(e)}
try{


}catch(e){_._DumpException(e)}
try{
_.fc=_.fc||{};_.fc.hk=_.r;_.fc.Cj=_.r;_.fc.af=_.r;_.fc.frameElement=_.r;_.fc=_.fc||{};
if(!_.fc.Qh){_.ic=function(a){var c=_.P.parse(a.data);if(c&&c.f){var f=_.S.Pb(c.f);(!_.gc||!("undefined"!==typeof a.origin?a.origin!==f:a.domain!==/^.+:\/\/([^:]+).*/.exec(f)[1]))&&(0,_.hc)(c,a.origin)}};_.gc=_.q;_.fc.Qh={Di:(0,_.y)("wpm"),b:(0,_.y)(_.q),S:function(a,c){_.R.N("rpc",_.r,function(a){if("true"===(0,window.String)((a&&a.rpc||{}).disableForceSecure))_.gc=_.t});_.hc=a;_.jc=c;"undefined"!=typeof window.addEventListener?window.addEventListener("message",_.ic,_.t):"undefined"!=typeof window.attachEvent&&
window.attachEvent("onmessage",_.ic);window.___jsl=window.___jsl||{};var f=window.___jsl;f.RPMQ=f.RPMQ||[];f.RPMQ.push(_.ic);(0,_.jc)("..",_.q);return _.q},xc:function(a){(0,_.jc)(a,_.q);return _.q},call:function(a,c,f){var g=_.S.Pb(a),h=_.S.bi(a);g?window.setTimeout(function(){h.postMessage(_.P.stringify(f),g)},0):".."!=a&&(0,_.Ma)("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message");return _.q}}};
_.fc=_.fc||{};
if(!_.fc.Pe){_.kc=_.fc;_.nc=function(a,c){function f(){a.apply({},arguments)}_.lc[c]=_.lc[c]||f;return _.mc+"."+c};_.uc=function(){if(_.oc===_.r&&window.document.body&&_.pc){var a=_.pc+"?cb="+window.Math.random()+"&origin="+_.qc+"&jsl=1",c=window.document.createElement("div");c.style.height="1px";c.style.width="1px";a='<object height="1" width="1" id="'+_.rc+'" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+
a+'" height="1" width="1"></embed></object>';window.document.body.appendChild(c);c.innerHTML=a;_.oc=c.firstChild}++_.sc;_.tc!==_.r&&(_.oc!==_.r||50<=_.sc)?window.clearTimeout(_.tc):_.tc=window.setTimeout(_.uc,100)};_.zc=function(){_.vc[".."]||((0,_.wc)(".."),_.xc++,50<=_.xc&&_.yc!==_.r?(window.clearTimeout(_.yc),_.yc=_.r):_.yc=window.setTimeout(_.zc,100))};_.Dc=function(){if(_.oc!==_.r&&_.oc.setup)for(;0<_.Cc.length;){var a=_.Cc.shift(),c=a.fp;_.oc.setup(a.Ld,".."===c?_.S.Mf:c,".."===c?"INNER":"OUTER")}_.tc!==
_.r&&window.clearTimeout(_.tc);_.tc=_.r};_.Ec=function(){!_.vc[".."]&&_.yc===_.r&&(_.yc=window.setTimeout(_.zc,100))};_.Fc=function(a,c,f){var c=_.S.Pb(a),g=_.S.Nb(a);_.oc["sendMessage_"+(".."===a?_.S.Mf:a)+"_"+g+"_"+(".."===a?"INNER":"OUTER")].call(_.oc,_.P.stringify(f),c);return _.q};_.Ic=function(a,c){var f=_.P.parse(a),g=f._scr;g?((0,_.Gc)(g,_.q),_.vc[g]=_.q,".."!==g&&(0,_.wc)(g,_.q)):window.setTimeout(function(){(0,_.Hc)(f,c)},0)};_.wc=function(a,c){var f=_.S.Mf,g={};g._scr=c?"..":f;g._pnt=f;
(0,_.Fc)(a,f,g)};_.rc="___xpcswf";_.pc=_.r;_.Jc=_.t;_.Hc=_.r;_.Gc=_.r;_.oc=_.r;_.Cc=[];_.tc=_.r;_.sc=0;_.xc=0;_.yc=_.r;_.vc={};_.qc=window.location.protocol+"//"+window.location.host;window.___jsl=window.___jsl||{};_.Kc=window.___jsl._fm={};_.mc="___jsl._fm";_.lc=_.Kc;_.R.N("rpc",_.r,function(a){_.Jc&&(_.pc=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});(0,_.nc)(_.Dc,"ready");(0,_.nc)(_.Ec,"setupDone");(0,_.nc)(_.Ic,"receiveMessage");_.kc.Pe={Di:(0,_.y)("flash"),b:(0,_.y)(_.q), S:function(a,c){_.Hc=a;_.Gc=c;return _.Jc=_.q},xc:function(a,c){_.Cc.push({Ld:c,fp:a});_.oc===_.r&&_.tc===_.r&&(_.tc=window.setTimeout(_.uc,100));return _.q},call:_.Fc,Ul:_.Ic,d:_.Dc,i:_.Ec}};
if(!window.gadgets||!window.gadgets.rpc){_.Qc=function(a,c){if(!_.Lc[a]){var f=_.Mc;c||(f=_.Nc);_.Lc[a]=f;for(var g=_.Oc[a]||[],h=0;h<g.length;++h){var k=g[h];k.t=_.Pc[a];f.call(a,k.f,k)}_.Oc[a]=[]}};_.Vc=function(a,c,f,g,h){function k(){_.Rc=_.q}if(!_.Pc[c]||_.Pc[c]!==f)(0,_.Ma)("Invalid auth token. "+_.Pc[c]+" vs "+f),(0,_.Sc)(c,2);h.onunload=function(){_.Tc[c]&&!_.Rc&&((0,_.Sc)(c,1),_.S.Gd(c))};_.Uc||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",k,_.t):"undefined"!=
typeof window.attachEvent&&window.attachEvent("onunload",k),_.Uc=_.q);g=_.P.parse((0,window.decodeURIComponent)(g))};_.Yc=function(a,c){if(a&&"string"===typeof a.s&&"string"===typeof a.f&&a.a instanceof window.Array)if(_.Pc[a.f]&&_.Pc[a.f]!==a.t&&((0,_.Ma)("Invalid auth token. "+_.Pc[a.f]+" vs "+a.t),(0,_.Sc)(a.f,2)),"__ack"===a.s)window.setTimeout(function(){(0,_.Qc)(a.f,_.q)},0);else{a.c&&(a.callback=function(c){_.S.call(a.f,(a.g?"legacy__":"")+"__cb",_.r,a.c,c)});if(c){var f=(0,_.Wc)(c);a.origin=
c;var g=a.r;if(!g||(0,_.Wc)(g)!=f)g=c;a.referer=g}f=(_.Xc[a.s]||_.Xc[""]).apply(a,a.a);a.c&&"undefined"!==typeof f&&_.S.call(a.f,"__cb",_.r,a.c,f)}};_.Wc=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));var a=a.substring(0,a.indexOf("://")),f="",g=c.indexOf(":");if(-1!=g){var h=c.substring(g+
1),c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f};_.Zc=function(a){if("/"==a.charAt(0)){var c=a.indexOf("|");return{id:0<c?a.substring(1,c):a.substring(1),origin:0<c?a.substring(c+1):_.r}}return _.r};_.$c=function(a){if("undefined"===typeof a||".."===a)return window.parent;var c=(0,_.Zc)(a);if(c)return window.top.frames[c.id];a=(0,window.String)(a);return(c=window.frames[a])?c:(c=window.document.getElementById(a))&&c.contentWindow?c.contentWindow:_.r};
_.ad=function(a,c){if(_.Tc[a]!==_.q){"undefined"===typeof _.Tc[a]&&(_.Tc[a]=0);var f=(0,_.$c)(a);(".."===a||f!=_.r)&&_.Mc.xc(a,c)===_.q?_.Tc[a]=_.q:_.Tc[a]!==_.q&&10>_.Tc[a]++?window.setTimeout(function(){(0,_.ad)(a,c)},500):(_.Lc[a]=_.Nc,_.Tc[a]=_.q)}};_.cd=function(a){(a=_.bd[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a};_.ed=function(a,c,f){c&&!/http(s)?:\/\/.+/.test(c)&&
(0==c.indexOf("//")?c=window.location.protocol+c:"/"==c.charAt(0)?c=window.location.protocol+"//"+window.location.host+c:-1==c.indexOf("://")&&(c=window.location.protocol+"//"+c));_.bd[a]=c;"undefined"!==typeof f&&(_.dd[a]=!!f)};_.fd=function(a,c){c=c||"";_.Pc[a]=(0,window.String)(c);(0,_.ad)(a,c)};_.id=function(a){a=(a.passReferrer||"").split(":",2);_.gd=a[0]||"none";_.hd=a[1]||"origin"};_.jd=function(a){"true"===(0,window.String)(a.useLegacyProtocol)&&(_.Mc=_.fc.af||_.Nc,_.Mc.S(_.Yc,_.Qc))};_.ld=
function(a,c,f){if(".."===a){var g=f||_.kd.rpctoken||_.kd.ifpctok||"",a=function(a){a=a&&a.rpc||{};(0,_.id)(a);var f=a.parentRelayUrl||"",f=(0,_.Wc)(_.kd.parent||c)+f;(0,_.ed)("..",f,"true"===(0,window.String)(a.useLegacyProtocol));(0,_.jd)(a);(0,_.fd)("..",g)};!_.kd.parent&&c?a({}):_.R.N("rpc",_.r,a)}else a:{var h=_.r;if("/"!=a.charAt(0)){if(!_.Q)break a;(h=window.document.getElementById(a))||(0,_.l)((0,window.Error)("g`"+a))}var h=h&&h.src,k=c||_.S.na(h);(0,_.ed)(a,k);h=_.Q.X(h);(0,_.fd)(a,f||h.rpctoken)}};
_.Xc={};_.bd={};_.dd={};_.Pc={};_.md=0;_.nd={};_.Tc={};_.kd={};_.Lc={};_.Oc={};_.gd=_.r;_.hd=_.r;_.od=window.top!==window.self;_.pd=window.name;_.Sc=(0,_.w)();_.qd=window.console;_.rd=_.qd&&_.qd.log&&function(a){_.qd.log(a)}||(0,_.w)();_.sd=function(a){return function(){(0,_.rd)(a+": call ignored")}};_.Nc={getCode:(0,_.y)("noop"),isParentVerifiable:(0,_.y)(_.q),init:(0,_.sd)("init"),setup:(0,_.sd)("setup"),call:(0,_.sd)("call")};_.Q&&(_.kd=_.Q.X());_.Rc=_.t;_.Uc=_.t;_.Mc=function(){if("flash"==_.kd.rpctx)return _.fc.Pe;
if("rmr"==_.kd.rpctx)return _.fc.hk;var a="function"===typeof window.postMessage?_.fc.Qh:"object"===typeof window.postMessage?_.fc.Qh:window.ActiveXObject?_.fc.Pe?_.fc.Pe:_.fc.Cj?_.fc.Cj:_.fc.af:0<window.navigator.userAgent.indexOf("WebKit")?_.fc.hk:"Gecko"===window.navigator.product?_.fc.frameElement:_.fc.af;a||(a=_.Nc);return a}();_.Xc[""]=function(){(0,_.rd)("Unknown RPC service: "+this.s)};_.Xc.__cb=function(a,c){var f=_.nd[a];f&&(delete _.nd[a],f.call(this,c))};_.S={ga:function(a){"function"===
typeof a.Ko&&(_.Sc=a.Ko)},N:function(a,c){("__cb"===a||"__ack"===a)&&(0,_.l)((0,window.Error)("h"));""===a&&(0,_.l)((0,window.Error)("i"));_.Xc[a]=c},Xb:function(a){("__cb"===a||"__ack"===a)&&(0,_.l)((0,window.Error)("j"));""===a&&(0,_.l)((0,window.Error)("k"));delete _.Xc[a]},we:function(a){_.Xc[""]=a},Ee:function(){delete _.Xc[""]},Zd:(0,_.w)(),call:function(a,c,f,g){var a=a||"..",h="..";".."===a?h=_.pd:"/"==a.charAt(0)&&(h=_.S.na(window.location.href),h="/"+_.pd+(h?"|"+h:""));++_.md;f&&(_.nd[_.md]=
f);var k={s:c,f:h,c:f?_.md:0,a:window.Array.prototype.slice.call(arguments,3),t:_.Pc[a],l:!!_.dd[a]},m;a:if("bidir"===_.gd||"c2p"===_.gd&&".."===a||"p2c"===_.gd&&".."!==a){m=window.location.href;var p="?";if("query"===_.hd)p="#";else if("hash"===_.hd)break a;p=m.lastIndexOf(p);p=-1===p?m.length:p;m=m.substring(0,p)}else m=_.r;m&&(k.r=m);".."!==a&&(0,_.Zc)(a)==_.r&&!window.document.getElementById(a)||(m=_.Lc[a],!m&&(0,_.Zc)(a)!==_.r&&(m=_.Mc),0===c.indexOf("legacy__")&&(m=_.Mc,k.s=c.substring(8),k.c=
k.c?k.c:_.md),k.g=_.q,k.r=h,m?(_.dd[a]&&(m=_.fc.af),m.call(a,h,k)===_.t&&(_.Lc[a]=_.Nc,_.Mc.call(a,h,k))):_.Oc[a]?_.Oc[a].push(k):_.Oc[a]=[k])},de:_.cd,Zc:_.ed,Yc:_.fd,yc:_.ld,Nb:function(a){return _.Pc[a]},Gd:function(a){delete _.bd[a];delete _.dd[a];delete _.Pc[a];delete _.Tc[a];delete _.Lc[a]},ce:function(){return _.Mc.Di()},ue:function(a,c){4<a.length?_.Mc.Ul(a,_.Yc):_.Vc.apply(_.r,a.concat(c))},ve:function(a){a.a=window.Array.prototype.slice.call(a.a);window.setTimeout(function(){(0,_.Yc)(a)},
0)},na:_.Wc,Pb:function(a){var c=_.r,c=(0,_.cd)(a);c||(c=(c=(0,_.Zc)(a))?c.origin:".."==a?_.kd.parent:window.document.getElementById(a).src);return(0,_.Wc)(c)},S:function(){_.Mc.S(_.Yc,_.Qc)===_.t&&(_.Mc=_.Nc);_.od?(0,_.ld)(".."):_.R.N("rpc",_.r,function(a){a=a.rpc||{};(0,_.id)(a);(0,_.jd)(a)})},bi:_.$c,Tl:_.Zc,b:"__ack",Mf:_.pd||"..",j:0,i:1,d:2};_.S.S()}else if("undefined"==typeof _.S||!_.S)_.S=window.gadgets.rpc,_.S.ga=_.S.config,_.S.N=_.S.register,_.S.Xb=_.S.unregister,_.S.we=_.S.registerDefault,
_.S.Ee=_.S.unregisterDefault,_.S.Zd=_.S.forceParentVerifiable,_.S.call=_.S.call,_.S.de=_.S.getRelayUrl,_.S.Zc=_.S.setRelayUrl,_.S.Yc=_.S.setAuthToken,_.S.yc=_.S.setupReceiver,_.S.Nb=_.S.getAuthToken,_.S.Gd=_.S.removeReceiver,_.S.ce=_.S.getRelayChannel,_.S.ue=_.S.receive,_.S.ve=_.S.receiveSameDomain,_.S.na=_.S.getOrigin,_.S.Pb=_.S.getTargetOrigin,_.S.bi=_.S._getTargetWin,_.S.Tl=_.S._parseSiblingId;
(0,_.O)("gadgets.rpc.config",_.S.ga);(0,_.O)("gadgets.rpc.register",_.S.N);(0,_.O)("gadgets.rpc.unregister",_.S.Xb);(0,_.O)("gadgets.rpc.registerDefault",_.S.we);(0,_.O)("gadgets.rpc.unregisterDefault",_.S.Ee);(0,_.O)("gadgets.rpc.forceParentVerifiable",_.S.Zd);(0,_.O)("gadgets.rpc.call",_.S.call);(0,_.O)("gadgets.rpc.getRelayUrl",_.S.de);(0,_.O)("gadgets.rpc.setRelayUrl",_.S.Zc);(0,_.O)("gadgets.rpc.setAuthToken",_.S.Yc);(0,_.O)("gadgets.rpc.setupReceiver",_.S.yc);
(0,_.O)("gadgets.rpc.getAuthToken",_.S.Nb);(0,_.O)("gadgets.rpc.removeReceiver",_.S.Gd);(0,_.O)("gadgets.rpc.getRelayChannel",_.S.ce);(0,_.O)("gadgets.rpc.receive",_.S.ue);(0,_.O)("gadgets.rpc.receiveSameDomain",_.S.ve);(0,_.O)("gadgets.rpc.getOrigin",_.S.na);(0,_.O)("gadgets.rpc.getTargetOrigin",_.S.Pb);


}catch(e){_._DumpException(e)}
try{
_.td=_.pb=_.pb||{};_.ud={Sh:"bsh",Vh:"h"};window.___jsl=window.___jsl||{};_.td.Ud={Bm:function(){return window.___jsl[_.ud.Sh]},Ag:function(){return window.___jsl[_.ud.Vh]},zf:function(a){window.___jsl[_.ud.Sh]=a},Ro:function(a){window.___jsl[_.ud.Vh]=a}};


}catch(e){_._DumpException(e)}
try{
_.vd=window.iframer=window.iframer||{};_.T=window.iframes=window.iframes||{};

}catch(e){_._DumpException(e)}
try{
_.wd=function(a,c,f){var g=(0,window.RegExp)("([#].*&|[#])"+c+"=([^&#]*)","g"),c=(0,window.RegExp)("([?#].*&|[?#])"+c+"=([^&#]*)","g");if(a=a&&(g.exec(a)||c.exec(a)))try{f=(0,window.decodeURIComponent)(a[2])}catch(h){}return f};_.xd=function(a){var c=(0,_.N)("googleapis.config/sessionIndex");c==_.r&&(c=window.__X_GOOG_AUTHUSER);if(c==_.r){var f=window.google;f&&(c=f.authuser)}c==_.r&&(a==_.r&&(a=window.location.href),c=a?(0,_.wd)(a,"authuser")||_.r:_.r);return c==_.r?_.r:(0,window.String)(c)};
_.yd=function(a,c,f){a=(0,window.String)(a);if(((0,_.wd)(a,"authuser")||_.r)!=_.r||((0,_.wd)(a,"hd")||_.r)!=_.r)return a;c=(0,_.xd)(c);if(f){var g=a,h=g.match(/^((https?:)?\/\/[^\/?#]*)?(\/[^\/?#]+)\/[0-9]+([\/][^?#]*)([?#].*)?$/);if(h&&h[0]){var k=h[1],m=h[4],p=h[5];h[3]=="/"+f&&(g=(k||"")+(m||"/")+(p||""))}if((h=g.match(/^(((https?:)?\/\/[^\/?#]*)([\/][^?#]*)?|([\/][^?#]*))([?#].*)?$/))&&h[0])return k=h[2],a=h[4]||h[5],p=h[6],c!=_.r&&(g=(k||"")+"/"+f+"/"+(0,window.encodeURIComponent)(c)+(a||"/")+
(p||"")),g}f=c==_.r?(0,window.encodeURIComponent)("authuser")+"=0":c.match(/^([-a-z0-9]+[.])+[-a-z0-9]+$/)?[(0,window.encodeURIComponent)("authuser")+"=",(0,window.encodeURIComponent)((0,window.String)(c)),"&"+(0,window.encodeURIComponent)("hd")+"=",(0,window.encodeURIComponent)(c)].join(""):["authuser=",(0,window.encodeURIComponent)(c)].join("");a=a.split("#");c=a[0].indexOf("?");0>c?a[0]=[a[0],"?",f].join(""):(g=[a[0]],c<a[0].length-1&&g.push("&"),g.push(f),a[0]=g.join(""));return g=a.join("#")};
_.zd=_.yd;

}catch(e){_._DumpException(e)}
try{
_.T.D=_.T.D||{};_.T.D.Th="friendlyIframe";_.T.D.em=function(a){try{return!!a.document}catch(c){}return _.t};_.T.D.kc=function(a){var c=a.parent;return a!=c&&_.T.D.em(c)?_.T.D.kc(c):a};_.T.D.nj=function(a){try{return _.T.D.kc(a)!=a&&!!a.frameElement&&a.frameElement.name==_.T.D.Th}catch(c){return _.t}};_.T.D.Hn=function(a){var c=a.userAgent||"",a=a.product||"";return 0!=c.indexOf("Opera")&&-1==c.indexOf("WebKit")&&"Gecko"==a&&0<c.indexOf("rv:1.")};
if(window.ToolbarApi)_.Ad=window.ToolbarApi,_.Ad.ia=window.ToolbarApi.getInstance,_.Ad.prototype=window.ToolbarApi.prototype,_.C=_.Ad.prototype,_.C.Oj=_.Ad.prototype.openWindow,_.C.qi=_.Ad.prototype.closeWindow,_.C.rk=_.Ad.prototype.setOnCloseHandler,_.C.ni=_.Ad.prototype.canClosePopup,_.C.ck=_.Ad.prototype.resizeWindow;else{_.Bd=_.r;_.Ad=(0,_.w)();_.Ad.ia=function(){!_.Bd&&(window.external&&window.external.GTB_IsToolbar)&&(_.Bd=new _.Ad);return _.Bd};_.C=_.Ad.prototype;_.C.Oj=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.C.qi=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.C.rk=function(a,c){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,c)};_.C.ni=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.C.ck=function(a,c){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,c)};window.ToolbarApi=_.Ad;window.ToolbarApi.getInstance=_.Ad.ia};
if(!window.iframes||!window.iframes.open){_.Dd=/^[-_.0-9A-Za-z]+$/;_.Ed={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"};_.Id={onBeforeParentOpen:"beforeparentopen"};_.Jd={longdesc:_.q,name:_.q,src:_.q,frameborder:_.q,marginwidth:_.q,marginheight:_.q,scrolling:_.q,align:_.q,height:_.q,width:_.q,id:_.q,"class":_.q,style:_.q,title:_.q,tabindex:_.q,hspace:_.q,vspace:_.q,allowtransparency:_.q};_.Kd=
{onOpen:function(a){var c=a.ba();a.Ma(c.container||c.element);return a},onClose:function(a){a.remove()}};_.Ld=window.encodeURIComponent||window.escape;_.Md=function(a){(0,_.Ma)(a.join(""))};_.Nd=function(){_.T.kj++;return["I",_.T.kj,"_",(new window.Date).getTime()].join("")};_.Od=function(a){var c={allowtransparency:"true",frameborder:0,hspace:0,marginheight:0,marginwidth:0,scrolling:"no",style:"",tabindex:"0",vspace:0,width:"100%"},f;for(f in a)a.hasOwnProperty(f)&&(c[f]=a[f]);return c};_.Qd=function(a,
c,f){f=f||{};f.id||(f.id=a);f.name||(f.name=a);f.src||(f.src=c);a=(0,_.Od)(f);c=[];c.push("<iframe ");for(var g in a)a.hasOwnProperty(g)&&(_.Jd[g.toLowerCase()]?(f=(0,window.String)(a[g]),c.push(g),c.push('="'),c.push(_.Q.Yd("style"==g.toLowerCase()?(0,_.Pd)(f):f)),c.push('" ')):(0,_.Md)(['Iframe attribute "',g,'" not allowed.']));c.push("></iframe>");return c.join("")};_.Pd=function(a){if(!a)return"";for(var c=[],a=a.split(";"),f=0,g=a.length;f<g;++f){var h=a[f];0==h.length&&f+1==g||(h=h.split(":"),
2==h.length&&h[0].match(/^[ a-zA-Z_-]+$/)&&h[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?c.push(h.join(":")):(0,_.Md)(['Iframe style "',a[f],'" not allowed.']))}return c.join(";")};_.Rd=function(a){if(0==a.indexOf("http:")||0==a.indexOf("https:")||0==a.indexOf("javascript:"))return a;if(0==a.indexOf("//"))return window.location.protocol+a;if(0==a.indexOf("/"))return window.location.protocol+"//"+window.location.host+a;var c=window.location.protocol+"//"+window.location.host+window.location.pathname;return c.substring(0,
c.lastIndexOf("/")+1)+a};_.Sd=function(a){return a instanceof window.Array?a.join(","):a instanceof window.Object?_.P.stringify(a):a};_.Td=function(a,c,f){var g={},h=a.indexOf("#");-1==h?(g.hash=_.r,g.jd=a):(g.hash=a.substring(h+1),g.jd=a.substring(0,h));a=g.jd.indexOf("?");-1==a?g.Ed=_.r:(g.Ed=g.jd.substring(a+1),g.jd=g.jd.substring(0,a));var a=f?g.hash?[g.hash]:[]:g.Ed?[g.Ed]:[],k;for(k in c)c.hasOwnProperty(k)&&(h=(0,_.Sd)(c[k]),a.push([(0,_.Ld)(k),(0,_.Ld)(h)].join("=")));f?g.hash=a.join("&"):
g.Ed=a.join("&");return g.jd+(g.Ed?"?"+g.Ed:"")+(g.hash?"#"+g.hash:"")};_.Ud=(0,_.w)();_.Vd=function(){var a=(0,_.xd)(_.n);return a!==_.n&&a!==_.r&&""!==a?"u/"+a+"/":""};_.Wd=function(a){var c=_.Q.X().jsh||_.pb.Ud.Ag();!a.jsh&&c&&(a.jsh=c);c=_.Q.X()._bsh||_.pb.Ud.Bm();!a._bsh&&c&&(a._bsh=c)};_.Xd=function(a){a&&a.match(_.Dd)&&(0,_.za)("googleapis.config/gcv",a)};_.Yd=function(a){_.pb.Ud.Ro(a)};_.Zd=function(a){_.pb.Ud.zf(a)};_.$d=function(a,c){var f=c||{},g;for(g in a)a.hasOwnProperty(g)&&(f[g]=a[g]);
return f};_.ae=function(a){_.T.wf[a]||(_.T.wf[a]={},_.S.N(a,function(c,f){var g=this.f;if("string"==typeof c&&!(c in{})&&!(g in{})){var h=this.callback,k=_.T.wf[a][g],m;k&&window.Object.hasOwnProperty.call(k,c)?m=k[c]:window.Object.hasOwnProperty.call(_.T.td,a)&&(m=_.T.td[a]);if(m)return g=window.Array.prototype.slice.call(arguments,1),m._iframe_wrapped_rpc_&&h&&g.push(h),m.apply({},g)}(0,_.Md)(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',c,'" from frame "',g,
'".']);return _.r}));return _.T.wf[a]};_.be=function(a,c,f,g,h){var k=[],m;for(m in a)if(a.hasOwnProperty(m)){var p=c,s=f,u=a[m],v=g,A=(0,_.ae)(m);A[p]=A[p]||{};v=_.Q.yd(v,u);u._iframe_wrapped_rpc_&&(v._iframe_wrapped_rpc_=_.q);A[p][s]=v;k.push(m)}if(h)for(m in _.T.td)_.T.td.hasOwnProperty(m)&&k.push(m);return k.join(",")};_.ce=function(a,c,f){function g(g){var k=window.Array.prototype.slice.call(arguments,0),m=k[k.length-1];if("function"===typeof m){var p=m;k.pop()}k.unshift(c,a,p,f);var s;a:if(".."==
c||window.document.getElementById(c))s=window;else{for(m=0;m<_.T.rg.length;m++)try{var u=_.T.rg[m];if(u&&u.document&&(u.document||window.document).getElementById(c)){s=u;break a}}catch(v){}s=_.r}s?s==window?_.S.call.apply(_.S,k):(s=s.gadgets.rpc,s.call.apply(s,k)):(0,_.Md)(["RPC ",a,' not sent: target iframe "',c,'" not found.'])}g._iframe_wrapped_rpc_=_.q;return g};_.de=function(a,c,f){var g={};if(a&&a._methods)for(var a=a._methods.split(","),h=0;h<a.length;h++){var k=a[h];g[k]=(0,_.ce)(k,c,f)}return g};
_.ee=function(a){return a&&a.disableMultiLevelParentRelay?_.t:_.vd&&_.vd._open&&"inline"!=a.style&&a.inline!==_.q&&!(a.container&&("string"==typeof a.container&&window.document.getElementById(a.container)||window.document==(a.container.ownerDocument||a.container.document)))};_.fe=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)};_.ge=function(a,c){function f(){}f.prototype=c.prototype;a.prototype=new f};_.he=function(a,c,f,g,h,k,m,p){if(":"==a.charAt(0)){var a="iframes/"+a.substring(1),s=
a+"/params",u={},v=(0,_.N)(s);(0,_.za)(s,v||u);s=a+"/url";u=(u=(0,_.N)(a+"/url"))||"";u=u.replace(/:session_prefix:/g,(0,_.Vd)());u=u.replace(/:session_index:/g,(0,_.xd)(_.n)||"0");u=u.replace(/:socialhost:/g,(0,_.N)("iframes/:socialhost:"));(0,_.za)(s,(0,_.Rd)(u));a=(0,_.N)(a)}else a={url:(0,_.Rd)(a)};this.ga=a;this.openParams=this.o=c;this.qb=f||{};this.Wa=g;this.i=_.t;this.Xn(c.style);this.d={};this.Vc(function(){this.Vl(h);k&&this.Tf("close",k)});this.Tb=this.ac=m;this.wh=(p||[]).slice();m&&this.wh.unshift(m.U())};
_.C=_.he.prototype;_.C.ba=(0,_.x)("o");_.C.Oa=(0,_.x)("qb");_.C.Ob=(0,_.x)("Wa");_.C.Ba=(0,_.x)("Tb");_.C.Xn=function(a){if(!this.i)if(a=a&&!_.T.Be[a]&&_.T.fg[a]){this.j=[];var c=this;a(function(){c.i=_.q;for(var a=0,g=c.j.length;a<g;++a)c.j[a].call(c)})}else this.i=_.q};_.C.Vc=function(a){this.i?a.call(this):this.j.push(a)};_.C.Vl=function(a){var c=this.Im();if(c){if("function"===typeof c)c=c(this);else{var f={},g;for(g in c){var h=c[g];f[g]="function"===typeof h?_.Q.yd(c,h,this):h}c=f}for(var k in a)f=
c[k],"function"===typeof f&&this.Tf(a[k],_.Q.yd(c,f))}};_.C.Z=function(a,c){this.Vc(function(){this.Tf(a,c)})};_.C.Tf=function(a,c){this.d[a]=this.d[a]||[];this.d[a].push(c)};_.C.Ab=function(a,c){this.Vc(function(){var f=this.d[a];if(f)for(var g=0,h=f.length;g<h;++g)if(f[g]===c){f.splice(g,1);break}})};_.C.mb=function(a,c){var f,g=this.d[a];if(g)for(var h=window.Array.prototype.slice.call(arguments,1),k=0,m=g.length;k<m;++k)try{f=g[k].apply({},h)}catch(p){(0,_.Md)(['Exception when calling callback "',
a,'" with exception "',p.name,": ",p.message,'".'])}return f};_.C.Im=function(){var a=this.o.style;return a&&_.T.Be[a]?_.T.Be[a]:a?((0,_.Ua)(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),_.r):_.Kd};_.C.Te=function(a){return"number"==typeof a?{value:a,Hc:a+"px"}:"100%"==a?{value:100,Hc:"100%",tj:_.q}:_.r};_.U=function(a,c,f,g,h,k,m){_.he.call(this,a,c,f,g,_.Ed,h,k,m);this.id=c.id||(0,_.Nd)();this.lp=!!c.rpcToken;this.Dh=c.rpcToken||window.Math.round(1E9*(0,_.ab)());
var a=this.qb,c={},f=this.ga.params||{},p;for(p in a)"#"==p.charAt(0)&&(c[p.substring(1)]=a[p]),0==p.indexOf("fr-")&&(c[p.substring(3)]=a[p]),"#"==f[p]&&(c[p]=a[p]);for(var s in c)delete a["fr-"+s],delete a["#"+s],delete a[s];this.In=c;this.lg={};this.Vc(function(){this.mb("open");(0,_.$d)(this.lg,this)})};(0,_.ge)(_.U,_.he);_.C=_.U.prototype;_.C.Ma=function(a,c){if(!this.ga.url)return(0,_.Md)(["Cannot open iframe, empty URL."]),this;var f=window.location.protocol+"//"+window.location.host,g=this.id;
(0,_.Wd)(this.qb);var h=(0,_.$d)(this.Wa);h._ready=this.of;h._close=this.close;h._open=this.Pj;h._resizeMe=this.dk;h._renderstart=this.Lj;var k=this.In;k.id=g;k.parent=f;k.rpctoken=this.Dh;k._methods=(0,_.be)(h,g,"",this,_.q);f=this.kp();f=(0,_.Td)(f,k,_.q);a="string"===typeof a?window.document.getElementById(a):a;if(this.ba().allowPost&&2E3<f.length)this.ro(a,g,k,c);else if(this.lp)a.innerHTML=(0,_.Qd)(g,f,c);else if(_.T.D.Hn(window.navigator||{})){a.innerHTML=(0,_.Qd)(g,"about:blank",c);a.firstChild.src=
f;try{a.firstChild.contentDocument.location.href=f}catch(m){}}else{k=(0,_.Qd)(g,f,c);try{a.innerHTML=k}catch(p){h=window.document.createElement("div");for(h.innerHTML=k;a.firstChild;)a.removeChild(a.firstChild);a.appendChild(h.firstChild)}}this.Ec=a;this.nb=a.firstChild;_.T.Qc[g]=this;_.S.Yc(g,this.Dh);_.S.Zc(g,f);return this};_.C.am=function(a){var c=a.id,f=a.src,g=/#(?:.*&)?rpctoken=(\d+)/.exec(f),g=g&&g[1];this.id=c;this.Dh=g;this.Ec=a.parentNode;this.nb=a;_.T.Qc[c]=this;a=(0,_.$d)(this.Wa);a._ready=
this.of;a._close=this.close;a._open=this.Pj;a._resizeMe=this.dk;a._renderstart=this.Lj;(0,_.be)(a,c,"",this,_.q);_.S.Yc(c,g);_.S.Zc(c,f);return this};_.C.$l=function(a){var a=(0,_.Od)(a||{}),c;for(c in a)window.Object.prototype.hasOwnProperty.call(a,c)&&("style"==c?this.nb.style.cssText=a[c]:this.nb.setAttribute(c,a[c]))};_.C.ro=function(a,c,f,g){a.innerHTML=(0,_.Qd)(c,"",g);var h;-1!=window.navigator.userAgent.indexOf("WebKit")&&(h=a.firstChild,g=(0,_.Qd)(c+"_inner","",{style:"display:none"}),h=
h.contentWindow.document,h.open(),h.write(g));g=(0,_.Td)(this.ga.url,f,_.q);f=this.qb||{};g={action:g,method:"POST",target:c};c=window.document.createElement("form");c.style.display="none";for(var k in g)g.hasOwnProperty(k)&&(c[k]=g[k]);for(var m in f)f.hasOwnProperty(m)&&(k=window.document.createElement("input"),k.type="hidden",k.name=m,k.value=f[m],c.appendChild(k));a.appendChild(c);c.submit();c.parentNode.removeChild(c);h&&h.close()};_.C.Ta=function(a,c){this.lg[a]=c};_.C.U=(0,_.x)("id");_.C.da=
(0,_.x)("nb");_.C.Q=(0,_.x)("Ec");_.C.Db=(0,_.ba)("Ec");_.C.of=function(a){var c=(0,_.de)(a,this.id,"");this.Tb&&"function"==typeof this.Wa._ready&&(a._methods=(0,_.be)(c,this.Tb.U(),this.id,this,_.t),this.Wa._ready(a));(0,_.$d)(a,this);(0,_.$d)(c,this);this.mb("ready",a)};_.C.Lj=function(a){this.mb("renderstart",a)};_.C.yo=function(a,c,f){f._methods=(0,_.be)((0,_.de)(f,a,""),this.id,a,this,_.t);c(f)};_.C.close=function(a){a=this.mb("close",a);if(_.T.D.nj(window)){var c=window.frameElement,f=c.parentNode;
"friendlyIframeContainer"==f.className?(0,_.fe)(f):(0,_.fe)(c)}delete _.T.Qc[this.id];return a};_.C.remove=function(){(0,_.fe)(window.document.getElementById(this.id))};_.C.Pj=function(a){var c=(0,_.de)(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.Ec);if((0,_.ee)(a.openParams))new _.ie(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain);else if("expandable"===a.openParams.style&&a.openParams.inline!==_.q&&_.T.D.kc(window)!=
window)this.qo(a,c);else{var f=new _.U(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain),g=this;f.Vc(function(){var a=g.li(f);c._onopen(a)})}};_.C.qo=function(a,c){var f=_.T.D.kc(window),g={height:0,name:_.T.D.Th,style:"left:0;position:absolute;top:0;z-index:-10000",width:0},h=f.document.createElement("ins");h.className="friendlyIframeContainer";h.innerHTML=(0,_.Qd)("","about:blank",g);f.document.body.appendChild(h);f=h.firstChild.contentWindow;_.T.rg.push(f);g=f.document;h=['<html><body><script src="',
_.T.xg(),'"><\/script></body></html>'].join("");g.open();g.write(h);g.close();g=a.openParams.id||(0,_.Nd)();a.openParams.id=g;g=_.Q.yd(this,this.yo,g,c._ready);c._ready=g;var k=_.Q.yd(f,function(f,g){if(!f.le||"function"!=typeof f.le.open)return _.t;var h=f.le.open(a.url,a.openParams,a.params,c,c._onclose,g),h=g.li(h);c._onopen(h);return _.q},f,this),m=window.setInterval(function(){k()&&window.clearInterval(m)},10)};_.C.li=function(a){var c={childId:a.U()},f=a.lg;f._toclose=a.close;c._methods=(0,_.be)(f,
this.id,a.id,a,_.t);return c};_.C.dk=function(a){if(this.mb("resize",a)===_.n&&this.nb){var c=this.Te(a.width);c!=_.r&&(this.nb.style.width=c.Hc);a=this.Te(a.height);a!=_.r&&(this.nb.style.height=a.Hc);if(this.nb.parentElement&&(c!=_.r&&c.tj||a!=_.r&&a.tj))this.nb.parentElement.style.display="block"}};_.C.kp=function(){return(0,_.Td)(this.ga.url,this.qb,_.t)};_.ie=function(a,c,f,g,h,k,m){_.he.call(this,a,c,f,g,_.Id,h,k,m);this.url=a;this.b=_.r;this.G=(0,_.Nd)();this.Vc(function(){this.mb("beforeparentopen");
var a=(0,_.$d)(this.Wa);a._onopen=this.J;a._ready=this.of;a._onclose=this.F;this.qb._methods=(0,_.be)(a,"..",this.G,this,_.q);var a={},c;for(c in this.qb)a[c]=(0,_.Sd)(this.qb[c]);_.vd._open({url:this.ga.url,openParams:this.o,params:a,proxyId:this.G,openedByProxyChain:this.wh})})};(0,_.ge)(_.ie,_.he);_.ie.prototype.Gi=(0,_.x)("b");_.ie.prototype.J=function(a){this.b=a.childId;var c=(0,_.de)(a,"..",this.b);(0,_.$d)(c,this);this.close=c._toclose;_.T.Qc[this.b]=this;this.Tb&&this.Wa._onopen&&(a._methods=
(0,_.be)(c,this.Tb.U(),this.b,this,_.t),this.Wa._onopen(a))};_.ie.prototype.of=function(a){var c=(0,window.String)(this.b),f=(0,_.de)(a,"..",c);(0,_.$d)(a,this);(0,_.$d)(f,this);this.mb("ready",a);this.Tb&&this.Wa._ready&&(a._methods=(0,_.be)(f,this.Tb.U(),c,this,_.t),this.Wa._ready(a))};_.ie.prototype.F=function(a){if(this.Tb&&this.Wa._onclose)this.Wa._onclose(a);else return a=this.mb("close",a),delete _.T.Qc[this.b],a};_.je=function(a,c,f,g,h,k,m){_.he.call(this,a,c,f,g,_.Id,k,m);this.V=h;g._close=
this.close;this.onClosed=this.b;this.z=0;this.Vc(function(){this.mb("beforeparentopen");var a=(0,_.$d)(this.Wa);this.qb._methods=(0,_.be)(a,"..",this.G,this,_.q);(0,_.Wd)(this.qb);var a=(0,_.Td)(this.ga.url,this.qb,_.t),c=h.Oj(a);this.canAutoClose=function(a){a(h.ni(c))};h.rk(c,this);this.z=c})};(0,_.ge)(_.je,_.he);_.je.prototype.close=function(a){a=this.mb("close",a);this.V.qi(this.z);return a};_.je.prototype.b=function(){this.mb("close")};_.ke=function(a){return _.T.Be[a]};_.me=function(a,c){_.T.Be[a]=
c};_.ne=function(a){a=a||{};"auto"===a.height&&(a.height=_.Ya.yg());var c=window&&_.Ad&&_.Ad.ia();c?c.ck(a.width||0,a.height||0):_.vd&&_.vd._resizeMe&&_.vd._resizeMe(a)};_.oe=function(a){(0,_.Xd)(a)};_.Cd=function(){function a(a){var c=_.t;try{if(a!=_.r)var f=window.parent.frames[a.id],c=f.iframer.id==a.id&&f.iframes.openedId_(_.vd.id)}catch(m){}try{_.T.rf={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:c};for(a=0;a<_.T.qf.length;++a)_.T.qf[a](_.T.rf);
_.T.qf=[]}catch(p){}}_.T.Qc={};_.T.Be={};_.T.fg={};_.T.kj=0;_.T.rg=[];_.T.wf={};_.T.td={};_.T.rf=_.r;_.T.qf=[];_.S.N("_noop_echo",function(){var a=_.T.Qc[this.f],c=a&&a.Tb,f=_.r;c&&(f={},f.id=c.U(),f.proxyChain=a.wh);this.callback(f)});if(window.parent!=window){var c=_.Q.X();c.gcv&&(0,_.Xd)(c.gcv);var f=c.jsh;f&&(0,_.Yd)(f);(0,_.$d)((0,_.de)(c,"..",""),_.vd);(0,_.$d)(c,_.vd);window.setTimeout(function(){_.S.call("..","_noop_echo",a)},0)}_.T.aa=_.ke;_.T.ka=_.me;_.T.nk=_.oe;_.T.Wb=_.ne;_.T.Ei=function(a){return _.T.fg[a]};
_.T.Af=function(a,c){_.T.fg[a]=c};_.T.bk=_.ne;_.T.wk=_.oe;_.T.Sb={};_.T.Sb.get=_.ke;_.T.Sb.set=_.me;_.T.ci=function(a,c){(0,_.ae)(a);_.T.td[a]=c||window[a]};_.T.iq=function(a){delete _.T.td[a]};_.T.open=function(a,c,f,m,p,s){3==arguments.length?m={}:4==arguments.length&&"function"===typeof m&&(p=m,m={});var u="bubble"===c.style&&_.Ad&&_.Ad.ia();return u?new _.je(a,c,f,m,u,p,s):(0,_.ee)(c)?new _.ie(a,c,f,m,p,s):new _.U(a,c,f,m,p,s)};_.T.close=function(a,c){_.vd&&_.vd._close&&_.vd._close(a,c)};_.T.zb=
function(a,c,f){2==arguments.length&&"function"===typeof p&&(f=c,c={});var m=a||{};"height"in m||(m.height=_.Ya.yg());var p=c||{};m._methods=(0,_.be)(p,"..","",_.vd,_.q);_.vd&&_.vd._ready&&_.vd._ready(m,f)};_.T.Bg=function(a){_.T.rf?a(_.T.rf):_.T.qf.push(a)};_.T.mi=function(a,c,f){var m=window.Array.prototype.slice.call(arguments);_.T.Bg(function(a){a.sameOrigin&&(m.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.S.call.apply(_.S,m))})};_.T.Qj=function(a){return!!_.T.Qc[a]};
_.T.xg=function(){return["https://ssl.gstatic.com/gb/js/",(0,_.N)("googleapis.config/gcv")].join("")};_.T.Vj=function(a){var c={mouseover:1,mouseout:1};if(_.vd._event)for(var f=0;f<a.length;f++){var m=a[f];m in c&&_.Q.Sd(window.document,m,function(a){_.vd._event({event:a.type,timestamp:(new window.Date).getTime()})},_.q)}};_.T.pk=_.Yd;_.T.zf=_.Zd;_.T.Yn=_.Ud;_.T.mj=_.vd};(0,_.Cd)()}else _.T.ci=_.T.allow,_.T.mi=_.T.callSiblingOpener,_.T.close=_.T.close,_.T.xg=_.T.getGoogleConnectJsUri,_.T.aa=_.T.getHandler,
_.T.Ei=_.T.getDeferredHandler,_.T.Bg=_.T.getParentInfo,_.T.mj=_.T.iframer,_.T.open=_.T.open,_.T.Qj=_.T.openedId_,_.T.Vj=_.T.propagate,_.T.zb=_.T.ready,_.T.Wb=_.T.resize,_.T.nk=_.T.setGoogleConnectJsVersion,_.T.pk=_.T.setJsHint,_.T.zf=_.T.setBootstrapHint,_.T.ka=_.T.setHandler,_.T.Af=_.T.setDeferredHandler,_.he=window.IframeBase,_.he.prototype=window.IframeBase.prototype,_.C=_.he.prototype,_.C.Z=_.he.prototype.addCallback,_.C.Ob=_.he.prototype.getMethods,_.C.Ba=_.he.prototype.getOpenerIframe,_.C.ba=
_.he.prototype.getOpenParams,_.C.Oa=_.he.prototype.getParams,_.C.Ab=_.he.prototype.removeCallback,_.U=window.Iframe,_.U.prototype=window.Iframe.prototype,_.C=_.U.prototype,_.C.close=_.U.prototype.close,_.C.Ta=_.U.prototype.exposeMethod,_.C.U=_.U.prototype.getId,_.C.da=_.U.prototype.getIframeEl,_.C.Q=_.U.prototype.getSiteEl,_.C.Ma=_.U.prototype.openInto,_.C.remove=_.U.prototype.remove,_.C.Db=_.U.prototype.setSiteEl,_.C.Z=_.U.prototype.addCallback,_.C.Ob=_.U.prototype.getMethods,_.C.Ba=_.U.prototype.getOpenerIframe,
_.C.ba=_.U.prototype.getOpenParams,_.C.Oa=_.U.prototype.getParams,_.C.Ab=_.U.prototype.removeCallback,_.ie=window.IframeProxy,_.ie.prototype=window.IframeProxy.prototype,_.C=_.ie.prototype,_.C.Gi=_.ie.prototype.getTargetIframeId,_.C.Z=_.ie.prototype.addCallback,_.C.Ob=_.ie.prototype.getMethods,_.C.Ba=_.ie.prototype.getOpenerIframe,_.C.ba=_.ie.prototype.getOpenParams,_.C.Oa=_.ie.prototype.getParams,_.C.Ab=_.ie.prototype.removeCallback,window.IframeWindow&&(_.je=window.IframeWindow,_.je.prototype=window.IframeWindow.prototype, _.je.prototype.close=_.je.prototype.close,_.je.prototype.b=_.je.prototype.onClosed),_.T.Sb=window.iframes.handlers,_.T.Sb.get=_.T.Sb.get,_.T.Sb.set=_.T.Sb.set,_.T.bk=_.T.resizeMe,_.T.wk=_.T.setVersionOverride;
(0,_.O)("iframes.allow",_.T.ci);(0,_.O)("iframes.callSiblingOpener",_.T.mi);(0,_.O)("iframes.close",_.T.close);(0,_.O)("iframes.getGoogleConnectJsUri",_.T.xg);(0,_.O)("iframes.getHandler",_.T.aa);(0,_.O)("iframes.getDeferredHandler",_.T.Ei);(0,_.O)("iframes.getParentInfo",_.T.Bg);(0,_.O)("iframes.iframer",_.T.mj);(0,_.O)("iframes.open",_.T.open);(0,_.O)("iframes.openedId_",_.T.Qj);(0,_.O)("iframes.propagate",_.T.Vj);(0,_.O)("iframes.ready",_.T.zb);(0,_.O)("iframes.resize",_.T.Wb);
(0,_.O)("iframes.setGoogleConnectJsVersion",_.T.nk);(0,_.O)("iframes.setBootstrapHint",_.T.zf);(0,_.O)("iframes.setJsHint",_.T.pk);(0,_.O)("iframes.setHandler",_.T.ka);(0,_.O)("iframes.setDeferredHandler",_.T.Af);(0,_.O)("IframeBase",_.he);(0,_.O)("IframeBase.prototype.addCallback",_.he.prototype.Z);(0,_.O)("IframeBase.prototype.getMethods",_.he.prototype.Ob);(0,_.O)("IframeBase.prototype.getOpenerIframe",_.he.prototype.Ba);(0,_.O)("IframeBase.prototype.getOpenParams",_.he.prototype.ba);
(0,_.O)("IframeBase.prototype.getParams",_.he.prototype.Oa);(0,_.O)("IframeBase.prototype.removeCallback",_.he.prototype.Ab);(0,_.O)("Iframe",_.U);(0,_.O)("Iframe.prototype.close",_.U.prototype.close);(0,_.O)("Iframe.prototype.exposeMethod",_.U.prototype.Ta);(0,_.O)("Iframe.prototype.getId",_.U.prototype.U);(0,_.O)("Iframe.prototype.getIframeEl",_.U.prototype.da);(0,_.O)("Iframe.prototype.getSiteEl",_.U.prototype.Q);(0,_.O)("Iframe.prototype.openInto",_.U.prototype.Ma);
(0,_.O)("Iframe.prototype.remove",_.U.prototype.remove);(0,_.O)("Iframe.prototype.setSiteEl",_.U.prototype.Db);(0,_.O)("Iframe.prototype.addCallback",_.U.prototype.Z);(0,_.O)("Iframe.prototype.getMethods",_.U.prototype.Ob);(0,_.O)("Iframe.prototype.getOpenerIframe",_.U.prototype.Ba);(0,_.O)("Iframe.prototype.getOpenParams",_.U.prototype.ba);(0,_.O)("Iframe.prototype.getParams",_.U.prototype.Oa);(0,_.O)("Iframe.prototype.removeCallback",_.U.prototype.Ab);(0,_.O)("IframeProxy",_.ie);
(0,_.O)("IframeProxy.prototype.getTargetIframeId",_.ie.prototype.Gi);(0,_.O)("IframeProxy.prototype.addCallback",_.ie.prototype.Z);(0,_.O)("IframeProxy.prototype.getMethods",_.ie.prototype.Ob);(0,_.O)("IframeProxy.prototype.getOpenerIframe",_.ie.prototype.Ba);(0,_.O)("IframeProxy.prototype.getOpenParams",_.ie.prototype.ba);(0,_.O)("IframeProxy.prototype.getParams",_.ie.prototype.Oa);(0,_.O)("IframeProxy.prototype.removeCallback",_.ie.prototype.Ab);(0,_.O)("IframeWindow",_.je);
(0,_.O)("IframeWindow.prototype.close",_.je.prototype.close);(0,_.O)("IframeWindow.prototype.onClosed",_.je.prototype.b);(0,_.O)("iframes.util.getTopMostAccessibleWindow",_.T.D.kc);(0,_.O)("iframes.handlers.get",_.T.Sb.get);(0,_.O)("iframes.handlers.set",_.T.Sb.set);(0,_.O)("iframes.resizeMe",_.T.bk);(0,_.O)("iframes.setVersionOverride",_.T.wk);


}catch(e){_._DumpException(e)}
try{
_.pe=function(a){a=a.style;a.textIndent="0";a.margin="0";a.padding="0";a.background="transparent";a.borderStyle="none";a.cssFloat="none";a.styleFloat="none";a.lineHeight="normal";a.fontSize="1px";a.verticalAlign="baseline"};_.qe=function(a){var c=a.clientWidth;return"position:absolute;top:-10000px;width:"+(c?c+"px":a.style.width||"300px")+";margin:0px;border-style:none;"};
_.re=function(a,c){var f={};f.width=c?c.width:a.width;f.height=c?c.height:a.height;var g=a.da(),h=g.parentNode,k=f.width,f=f.height;(0,_.pe)(h);h.style.display="inline-block";g=g.style;g.position="static";g.left=0;g.top=0;g.visibility="visible";k&&(g.width=k+"px");f&&(g.height=f+"px");(k=c?c.title:_.r)&&a.da().setAttribute("title",k)};
_.se={open:function(a){var c=window.document.getElementById(a.ba().container);return a.Ma(c,{style:(0,_.qe)(c,a)})},attach:function(a,c){var f=window.document.getElementById(a.ba().container);a.am(c);a.$l({style:(0,_.qe)(f,a)})}};_.se.onready=_.re;_.se.onRenderStart=_.re;_.se.close=function(a){var c=a.Q();c&&c.removeChild(a.da())};_.T.ka("inline",_.se);


}catch(e){_._DumpException(e)}
try{
_.te=function(a,c){this.b=a;this.dc=c};_.ue=function(a){this.w=this.Kb=a;this.n=_.r;this.slf=0;this.ssh=_.t;this.sen=_.q;this.shl=this.itm=_.r};_.te.prototype.j=function(a){this.b.or(this.dc,a)};_.te.prototype.J=function(){this.b.oc(this.dc)};_.ue.prototype.sm=function(a,c){this.Kb.lk(new _.te(a,this));this.n=c};_.ue.prototype.sh=function(){this.Kb.show()};_.ue.prototype.hi=function(){this.Kb.fj()};_.ue.prototype.cl=function(){this.Kb.close()};_.ue.prototype.en=function(){this.Kb.enable()};_.ue.prototype.di=function(){this.Kb.disable()};_.ue.prototype.hl=function(a){this.Kb.Jm(a)};_.ue.prototype.vr=function(a,c){this.Kb.Hi(a,c)};


}catch(e){_._DumpException(e)}
try{


}catch(e){_._DumpException(e)}
try{
_.we=function(a){this.dc=a;this.La=0;this.ze=_.t;this.wi=_.q;this.Ce=_.r};_.xe=function(a){return 5==a.La||4==a.La};
_.ye=function(a,c,f){this.d=a||{};this.i=c||0;this.j=f||0;a={};c=(0,_.E)(this.ug,this);a.fc=c;c=(0,_.E)(this.vf,this);a.rc=c;c=(0,_.E)(this.Df,this);a.sc=c;c=(0,_.E)(this.ke,this);a.hc=c;c=(0,_.E)(this.Vd,this);a.cc=c;c=(0,_.E)(this.bj,this);a.os=c;c=(0,_.E)(this.aj,this);a.or=c;c=(0,_.E)(this.Zi,this);a.oh=c;c=(0,_.E)(this.Xi,this);a.oc=c;c=(0,_.E)(this.Yi,this);a.oe=c;c=(0,_.E)(this.$i,this);a.oi=c;this.b=a};
_.ze=function(a,c){var f=a.j-a.i;0<f&&(f=(0,window.setTimeout)((0,_.E)(function(){(0,_.xe)(c)||(c.La=4,this.Vd(c.ec()))},a),f),c.Ce=f)};_.Ae=function(a,c){c.Ce!=_.r&&((0,window.clearTimeout)(c.Ce),c.Ce=_.r)};_.Be=function(a,c){(0,_.Ae)(a,c);c.La=5;var f=a.d,g;for(g in f)f[g]==c&&delete f[g]};_.Ce=function(a,c){return a.d[c.n]};_.De=function(a){this.b=a};_.Ee=function(){_.ye.call(this)};
_.Fe=function(a){if(window.___jsl.man)a(window.___jsl.man);else if(window.gbar){var c=function(){var c=new _.De(window.gbar.wg);window.___jsl.man=c;a(c)};window.gbar.wg?c():window.gbar.qm(c)}else c=new _.Ee,window.___jsl.man=c,a(c)};_.Ge=function(){return window.___jsl.man};_.we.prototype.ec=(0,_.x)("dc");_.we.prototype.isEnabled=(0,_.x)("wi");_.we.prototype.ja=(0,_.ba)("wi");
_.C=_.ye.prototype;_.C.vf=function(a,c,f){try{a=a+(c!=_.r?"_"+c:""),f.sm(this.b,a),this.d[a]=new _.we(f)}catch(g){return _.t}return _.q};_.C.ug=function(a,c){var f=this.d[a+(c!=_.r?"_"+c:"")];return f?f.ec():_.r};_.C.Df=function(a){var c=(0,_.Ce)(this,a);if(c&&(2==c.La||3==c.La)&&c.isEnabled()&&!c.ze){try{a.sh()}catch(f){}c.ze=_.q}};_.C.ke=function(a){var c=(0,_.Ce)(this,a);if(c&&(2==c.La||3==c.La||(0,_.xe)(c))&&c.ze){try{a.hi()}catch(f){}c.ze=_.t}};
_.C.Vd=function(a){var c=(0,_.Ce)(this,a);if(c&&5!=c.La){try{this.ke(a),a.cl()}catch(f){}(0,_.Be)(this,c)}};_.C.bj=function(a){var c=(0,_.Ce)(this,a);c&&0==c.La&&(this.i?(a=(0,window.setTimeout)((0,_.E)(function(){(0,_.xe)(c)||(0,_.ze)(this,c)},this),this.i),c.Ce=a):(0,_.ze)(this,c),c.La=1)};_.C.aj=function(a){if((a=(0,_.Ce)(this,a))&&!(0,_.xe)(a)&&1==a.La)(0,_.Ae)(this,a),a.La=3};_.C.Zi=function(a){if((a=(0,_.Ce)(this,a))&&!(0,_.xe)(a))a.ze=_.t};
_.C.Xi=function(a){var c=(0,_.Ce)(this,a);if(c&&!(0,_.xe)(c)){try{this.ke(a)}catch(f){}(0,_.Be)(this,c)}};_.C.Yi=function(a){if((a=(0,_.Ce)(this,a))&&!(0,_.xe)(a))a.La=4,this.Vd(a.ec())};_.C.$i=function(a,c){var f=(0,_.Ce)(this,a);f&&!(0,_.xe)(f)&&(2<=c&&4>=c&&!(0,_.xe)(f))&&((0,_.Ae)(this,f),f.La=2)};
_.C=_.De.prototype;_.C.vf=function(a,c,f){return this.b.rc(a,c,f)};_.C.ug=function(a,c){return this.b.fc(a,c)};_.C.Df=function(a){this.b.sc(a)};_.C.ke=function(a){this.b.hc(a)};_.C.Vd=function(a){this.b.cc(a)};_.C.bj=function(a){this.b.os(a)};_.C.aj=function(a,c){this.b.or(a,c)};_.C.Zi=function(a){this.b.oh(a)};_.C.Xi=function(a){this.b.oc(a)};_.C.Yi=function(a,c,f,g,h,k){this.b.oe(a,c,f,g,h,k)};_.C.$i=function(a,c,f,g){this.b.oi(a,c,f,g)};
(0,_.F)(_.Ee,_.ye);

}catch(e){_._DumpException(e)}
try{
_.He=function(a,c){var f=(0,_.na)(_.Ie,a,(0,_.pa)());return(0,_.na)(f,c,(0,_.pa)())};_.Je=function(a,c,f){var g=_.r;c&&f&&(g=(0,_.He)(c,f)[a]);return g||_.Ke[a]};_.Le=function(a){this.t={};this.tick=function(a,f,g){this.t[a]=[g!=_.n?g:(new window.Date).getTime(),f]};this.tick("start",_.r,a)};
_.Me=function(a,c,f){for(var g=c?c+f:"gapi",h=(0,_.na)(_.Ne,g,(0,_.pa)()),k=_.Oe[a]||[],m=0;m<k.length;++m){var p=k[m],s=h,u=p[0],v=a,A=c,B=f,p=(0,_.Je)(p[1],A,B),v=(0,_.Je)(v,A,B);s[u]=p&&v?v-p:_.r}_.Pe[a]&&_.Qe&&((0,_.Re)("gapi"),(0,_.Re)(g,c,f))};_.Se=function(a,c){for(var c=c||[],f=[],g=0;g<c.length;g++)f.push(a+c[g]);return f};
_.Te=function(a,c,f){var g=[],h="m"+(_.Ue?"1":"0");g.push(h);g.push("l"+((0,_.N)("isPlusUser")?"1":"0"));a&&c&&(a="n"+c,g.push(a),"0"==c&&g.push(h+a));return(0,_.Se)(f?"e"+f:"",g)};
_.Re=function(a,c,f){var g=_.Ca.__gapi_jstiming__,h=new g.Timer(0);h.name=c||"gapi";var k=_.t,m=_.Ne[a];h.tick("_start",_.r,0);for(var p in m)h.tick(p,"_start",m[p]),k=_.q;_.Ne[a]=(0,_.pa)();if(k){a=[];k=(0,_.N)("lexps");a=a.concat((0,_.Se)("e",k));a=a.concat((0,_.Te)(c,f));for(m=0;m<_.Ve.length;m++)p=_.Ve[m],0<=_.oa.call(k,p)&&(a=a.concat((0,_.Te)(c,f,p)));a=(0,_.Se)("abc_",a);g.report(h,{e:a.join(",")})}};_.We=function(a,c,f,g){_.Pe[f]=_.Pe[f]||!!g;(0,_.na)(_.Oe,f,[]);_.Oe[f].push([a,c])};
_.Xe=(0,_.na)(_.Ea,"perf",(0,_.pa)());_.Ke=(0,_.na)(_.Xe,"g",(0,_.pa)());_.Ie=(0,_.na)(_.Xe,"i",(0,_.pa)());_.Ye=(0,_.na)(_.Xe,"r",[]);_.Pe=(0,_.pa)();_.Oe=(0,_.pa)();_.Ze=new _.Le;window.__gapi_jstiming__={Timer:_.Le,load:_.Ze};if(window.performance&&window.performance.timing){_.$e=window.performance.timing;_.af=window.__gapi_jstiming__.load;_.bf=_.$e.navigationStart;_.cf=_.$e.responseStart;0<_.bf&&_.cf>=_.bf&&(_.af.tick("_wtsrt",_.n,_.bf),_.af.tick("wtsrt_","_wtsrt",_.cf),_.af.tick("tbsd_","wtsrt_"))}
try{_.df=_.r;window.chrome&&window.chrome.csi&&(_.df=window.Math.floor(window.chrome.csi().pageT),_.af&&0<_.bf&&(_.af.tick("_tbnd",_.n,window.chrome.csi().startE),_.af.tick("tbnd_","_tbnd",_.bf)));_.df==_.r&&window.gtbExternal&&(_.df=window.gtbExternal.pageT());_.df==_.r&&window.external&&(_.df=window.external.pageT,_.af&&0<_.bf&&(_.af.tick("_tbnd",_.n,window.external.startE),_.af.tick("tbnd_","_tbnd",_.bf)));_.df&&(window.__gapi_jstiming__.pt=_.df)}catch(ef){};
if(window.__gapi_jstiming__){window.__gapi_jstiming__.ki={};window.__gapi_jstiming__.Co=1;_.ff=function(a,c,f){var g=a.t[c],h=a.t.start;if(g&&(h||f))return g=a.t[c][0],f!=_.n?h=f:h=h[0],g-h};window.__gapi_jstiming__.getTick=_.ff;window.__gapi_jstiming__.getLabels=function(a){var c=[],f;for(f in a.t)c.push(f);return c};_.gf=function(a,c,f){var g="";window.__gapi_jstiming__.pt&&(g+="&srt="+window.__gapi_jstiming__.pt);try{window.external&&window.external.tran?g+="&tran="+window.external.tran:window.gtbExternal&&
window.gtbExternal.tran?g+="&tran="+window.gtbExternal.tran():window.chrome&&window.chrome.csi&&(g+="&tran="+window.chrome.csi().tran)}catch(h){}var k=window.chrome;if(k&&(k=k.loadTimes)){k().wasFetchedViaSpdy&&(g+="&p=s");if(k().wasNpnNegotiated){var g=g+"&npn=1",m=k().npnNegotiatedProtocol;m&&(g+="&npnv="+(window.encodeURIComponent||window.escape)(m))}k().wasAlternateProtocolAvailable&&(g+="&apa=1")}var p=a.t,s=p.start,k=[],m=[],u;for(u in p)if("start"!=u&&0!=u.indexOf("_")){var v=p[u][1];v?p[v]&&
m.push(u+"."+(0,_.ff)(a,u,p[v][0])):s&&k.push(u+"."+(0,_.ff)(a,u))}if(c)for(var A in c)g+="&"+A+"="+c[A];(c=f)||(c="https:"==window.document.location.protocol?"https://csi.gstatic.com/csi":"http://csi.gstatic.com/csi");a=[c,"?v=3","&s="+(window.__gapi_jstiming__.sn||"gwidget")+"&action=",a.name,m.length?"&it="+m.join(","):"","",g,"&rt=",k.join(",")].join("");if(!a)return"";var g=new window.Image,B=window.__gapi_jstiming__.Co++;window.__gapi_jstiming__.ki[B]=g;g.onload=g.onerror=function(){window.__gapi_jstiming__&&
delete window.__gapi_jstiming__.ki[B]};g.src=a;g=_.r;return a};window.__gapi_jstiming__.report=function(a,c,f){if("prerender"==window.document.webkitVisibilityState){var g=_.t,h=function(){if(!g){c?c.prerender="1":c={prerender:"1"};var k;"prerender"==window.document.webkitVisibilityState?k=_.t:((0,_.gf)(a,c,f),k=_.q);k&&(g=_.q,window.document.removeEventListener("webkitvisibilitychange",h,_.t))}};window.document.addEventListener("webkitvisibilitychange",h,_.t);return""}return(0,_.gf)(a,c,f)}};
_.Ve=[73,74];_.Ue=window.navigator.userAgent.match(/iPhone|iPad|Android|PalmWebOS|Maemo|Bada/);_.Ne=(0,_.na)(_.Xe,"_c",(0,_.pa)());_.Qe=window.Math.random()<((0,_.N)("csi/rate")||0);(0,_.We)("blt","bs0","bs1");(0,_.We)("psi","ps0","ps1");(0,_.We)("wci","wrs","wdc");(0,_.We)("wdi","wrs","wrdi");(0,_.We)("wdt","bs0","wrdt");(0,_.We)("wri","wrs","wrri",_.q);(0,_.We)("wrt","bs0","wrrt");(0,_.We)("wji","wje0","wje1",_.q);(0,_.We)("wjli","wjl0","wjl1");(0,_.We)("rpcqi","rqe","rqd"); if("function"!==typeof _.Ye){for(_.hf;_.hf=_.Ye.shift();)_.Me.apply(_.r,_.hf);_.Ye=_.Xe.r=_.Me};


}catch(e){_._DumpException(e)}
try{
_.jf=function(a,c,f,g){(0,_.He)(c,f)[a]=g||(new window.Date).getTime();"function"===typeof _.Ye?(0,_.Ye)(a,c,f):_.Ye.push([a,c,f])};_.kf=function(a){var c=(0,_.N)(a);return"undefined"!==typeof c?c:(0,_.N)("gwidget/"+a)};_.lf=function(a){return function(c){var f=a;"number"===typeof c?f=c:"string"===typeof c&&(f=c.indexOf("px"),-1!=f&&(c=c.substring(0,f)),f=(0,window.parseInt)(c,10));return f}};_.mf=function(a){"string"===typeof a&&(a=window[a]);return"function"===typeof a?a:_.r};
_.nf=function(a){return a.bp&&window.gbar&&window.gapi.load};_.of=function(a,c,f,g){return _.T.open(a,c,f,g)};_.pf=function(a,c){for(var f in _.qf)if(_.qf.hasOwnProperty(f)){var g=_.qf[f][1];g&&!c.hasOwnProperty(g)&&(c[g]=a[g])}return c};_.rf=function(a,c){var f={},g;for(g in a)a.hasOwnProperty(g)&&(f[a[g][1]||g]=(a[g]&&a[g][0]||_.uf)(c[g],c,_.vf));return f};_.wf=function(a,c,f,g){var h=(0,_.rf)(a.ga,f);a.$j.push({element:c,ga:h,Fd:(0,_.pf)(h,(0,_.rf)(a.Sj,f)),Id:g,mm:!!f["data-onload"]})}; _.xf=function(a){function c(){for(var c=a.$j,g=a.vh;0<c.length;)g(c.shift())}(0,_.nf)(a)?(0,_.Fe)(c):c()};_.uf=function(a){return a};_.yf=function(){};_.zf=function(a){this.d=a;this.b=_.r};_.Af={};
_.Cf=["div"];_.Df="onload";_.Ef=_.q;_.vf=_.r;_.vf=(0,_.N)();(0,_.N)("gwidget");_.Ff=(0,_.kf)("parsetags");_.Df="explicit"===_.Ff||"onload"===_.Ff?_.Ff:_.Df;_.Gf=(0,_.kf)("google_analytics");"undefined"!==typeof _.Gf&&(_.Ef=!!_.Gf);_.Hf={};_.Hf.width=[(0,_.lf)(450)];_.Hf.height=[(0,_.lf)(24)];_.Hf.callback=[_.mf];_.Hf.onready=[_.mf];_.Hf.lang=[function(){return(0,_.kf)("lang")||"en-US"},"hl"];_.Hf.iloader=[function(){return _.Ea.ILI},"iloader"];_.qf=_.Hf;
_.Bf={cb:function(a){function c(a){for(var c={},f=0;f<a.length;++f)c[a[f].toLowerCase()]=1;c[h.Jk]=1;h.lh=c}function f(){"onload"===_.Df&&p.go()}var g,h={};h.Ib=a[0];h.If=-1;h.Ik="___"+h.Ib+"_";h.Jk="g:"+h.Ib;h.Ln="g-"+h.Ib;h.$j=[];h.ga={};h.Yf=[];h.mg=[];a[1]&&(h.Sj=a[1]);h.ga=a[2]||{};for(var k in _.qf)_.qf.hasOwnProperty(k)&&!h.ga.hasOwnProperty(k)&&(h.ga[k]=_.qf[k]);a[3]&&(h.Yf=a[3]);a[4]&&c(a[4]);a[5]&&(h.Hd=a[5]);h.bp=a[7]===_.q;h.vo=a[8];h.lh||c(_.Cf);if(a=a[6])if("number"==typeof a.length){h.mg=
a;for(var m=a.length-1;0<=m;--m)h.ga[a[m]]=[_.mf]}else for(m in a)a.hasOwnProperty(m)&&!h.ga.hasOwnProperty(m)&&(h.mg.push(m),h.ga[m]=a[m]);h.vh=function(a){function c(){jp||(jp=_.q,f(),kp&&(0,_.jf)("wrrt",Fd,Gd),(0,_.jf)("wrri",Fd,Gd))}function f(){lp||(lp=_.q,vb.da(),kp&&(0,_.jf)("wrdt",Fd,Gd),(0,_.jf)("wrdi",Fd,Gd))}function g(a){var a=a||vb,c=vb.Te(a.width);c&&ah.style.width!=c.Hc&&(ah.style.width=c.Hc);if((a=vb.Te(a.height))&&ah.style.height!=a.Hc)ah.style.height=a.Hc}h.If++;(0,_.jf)("wrs",h.Ib,
(0,window.String)(h.If));var k=[];h.Hd&&(k[0]=a.element,k[1]=a.Id,h.Hd("s",k),a.Id=k[1]);var m=a.element,p=m.parentNode,s=a.ga;if(0===a.Id){var v=window.document.createElement("div");p.insertBefore(v,m);p.removeChild(m);m=v}v=m.style;if(m.id){if(3===a.Id&&0===m.id.indexOf(h.Ik)){var u=m.nextSibling;u&&(u.getAttribute&&u.getAttribute("data-gapistub"))&&p.removeChild(u);v.cssText=""}}else{var p=m,u=h.Ik,ra=h.Ib,Ia=(0,_.na)(_.Ea,"WI",(0,_.pa)());window.Object.prototype.hasOwnProperty.call(Ia,ra)||(Ia[ra]=
0);var Ba=Ia[ra];Ia[ra]=Ba+1;p.id=u+Ba}s.height&&(v.height=s.height+"px");s.width&&(v.width=s.width+"px");v.display||(v.display="inline-block");(0,_.nf)(h)&&(v.display="none");(0,_.pe)(m);var ve=":"+h.Ib;":plus"==ve&&(a.Fd&&a.Fd.action)&&(ve+="_"+a.Fd.action);var v={},p=h.Yf[0],u=s.callback,mp=h.Yf[1];if(mp&&_.Ef)var mw=u||(0,_.w)(),u=function(a){var c=mp(a);if(c&&window._gat)try{var f=window._gat._getTrackerByName("~0");f&&"UA-XXXXX-X"!=f._getAccount()?f._trackSocial("Google",c,a.href||_.r):window._gaq&&
window._gaq.push(["_trackSocial","Google",c,a.href||_.r])}catch(g){}mw(a)};p&&u&&(v[p]=u);p=h.mg;for(u=p.length-1;0<=u;--u){var hb=p[u];(ra=s[hb])&&(v[hb]=ra)}p={};for(hb in a.Fd)a.Fd[hb]!=_.r&&(p[hb]=a.Fd[hb]);hb={container:m.id,style:"inline",height:s.height,width:s.width};if(3===a.Id){if(!_.T.aa("attach")){var Hd={},sf=_.T.aa("inline"),Bc;for(Bc in sf)sf.hasOwnProperty(Bc)&&(Hd[Bc]=sf[Bc]);Hd.open=function(a){var c;a:{c=window.document.getElementById(a.ba().container).getElementsByTagName("IFRAME");
for(var f=0;f<c.length;++f){var g=c[f];if(g.id&&/^I\d+_\d+$/.test(g.id)){c=g;break a}}c=_.n}return c?sf.attach(a,c):sf.open(a)};_.T.ka("attach",Hd)}hb.style="attach"}else if((0,_.nf)(h)){hb._ct=h.Ib;hb._ci=h.If;if(!_.T.aa("inline-managed")){Bc={};var tf=_.T.aa("inline");for(Hd in tf)tf.hasOwnProperty(Hd)&&(Bc[Hd]=tf[Hd]);Bc.open=function(a){tf.open(a);var c=new _.ue(new _.zf(a));(0,_.Ge)().vf(a.ba()._ct,a.ba()._ci,c)&&(a=c[_.Af.Zk.el],a.b&&(a=a.b,a.b.os(a.dc)))};Bc.onready=function(a){tf.onready(a);
var c=(0,_.Ge)();if(a=c.ug(a.ba()._ct,a.ba()._ci)){var f=a[_.Af.Zk.el];f.b&&f.b.j({});c.Df(a)}};_.T.ka("inline-managed",Bc)}hb.style="inline-managed"}h.Hd&&(k[2]=hb,k[3]=p,k[4]=v,h.Hd("i",k),a.Id=k[1]);var vb=function(a){var c=_.of.apply(_.r,[ve].concat([].slice.call(arguments,0)));if(s.onready){var f=_.t,g=function(){f||(f=_.q,s.onready.call(_.r))};c.Z("ready",g);c.Z("renderstart",g)}(0,_.yf)(c);return c}(hb,p,v),ah=m;vb.Z("ready",g);vb.Z("renderstart",g);vb.Z("resize",g);var kp=a.mm,Fd=h.Ib,Gd=
(0,window.String)(h.If),lp=_.t;vb.Z("renderstart",f);var jp=_.t;vb.Z("ready",c);_.S.N("widget-interactive-"+vb.id,c);_.S.N("widget-csi-tick-"+vb.id,function(a,c,f){"wdc"===a||"wci"===a?(0,_.jf)("wdc",Fd,Gd,f):"wje0"===a||"wji_"===a?(0,_.jf)("wje0",Fd,Gd,f):("wje1"===a||"wji"===a)&&(0,_.jf)("wje1",Fd,Gd,f)});k[5]=vb;h.Hd&&h.Hd("e",k)};g=h;if(m=g.vo)for(a=0;a<m.length;a++)(new window.Image).src=m[a];var p={O:function(a,c,f){a=("string"===typeof a?window.document.getElementById(a):a)||_.n;c=c||{};c.callback=
f||c.callback;a&&1===a.nodeType&&(0,_.wf)(g,a,c,1);(0,_.xf)(g)},go:function(a){if(a=("string"===typeof a?window.document.getElementById(a):a)||window.document.body){var c;c=[];for(var f=a.getElementsByTagName("iframe"),h={},k=0;k<f.length;++k){var m=f[k].parentNode,p=m.id;if(p&&!h[p]){var s;a:{s=g;var v=m,u=v.getAttribute("data-gwattr");if(u!=_.r){for(var u=u.split(":"),ra={},Ia=0;Ia<u.length;++Ia){var Ba=u[Ia].split("="),ve=window.decodeURIComponent(Ba[0]),Ba=window.decodeURIComponent(Ba[1]);ra[ve]=
Ba}if(ra[">type"]===s.Ib){v.removeAttribute("data-gwattr");s=ra;break a}}s=_.n}s&&(c.push({element:m,Wf:s}),h[p]=1)}}for(f=0;f<c.length;++f)h=c[f],(0,_.wf)(g,h.element,h.Wf,3);c=[];a=a.getElementsByTagName("*");f=(0,window.RegExp)("(?:^|\\s)"+g.Ln+"(?:$|\\s)");for(h=0;h<a.length;++h)if(k=a[h],m=k.nodeName.toLowerCase(),!k.getAttribute("data-gapistub")&&(g.lh[m]||g.lh["*"])){p="";if(m!==g.Jk&&(p="data-",!f.test(k.className||k.getAttribute("class"))))continue;s=m={};v=g.Sj;u=k;ra=p;Ia=_.n;for(Ia in v)v.hasOwnProperty(Ia)&&
(s[Ia]=u.getAttribute(ra+Ia));s=m;v=g.ga;u=k;ra=_.n;for(ra in v)v.hasOwnProperty(ra)&&(s[ra]=u.getAttribute(p+ra));c.push({element:k,Wf:m})}for(f=0;f<c.length;++f)h=c[f],(0,_.wf)(g,h.element,h.Wf,0);(0,_.xf)(g)}},b:function(){_.Ea.WI=(0,_.pa)()}},m=g.Ib,a=(0,_.na)(_.Ea,"sws",[]);if(!(0<=_.oa.call(a,m))){if("complete"!==_.Da.readyState)try{f()}catch(s){}if("complete"===_.Da.readyState)f();else{var u=_.t,v=function(){if(!u)return u=_.q,f.apply(this,arguments)};_.Ca.addEventListener?(_.Ca.addEventListener("load", v,_.t),_.Ca.addEventListener("DOMContentLoaded",v,_.t)):_.Ca.attachEvent&&(_.Ca.attachEvent("onreadystatechange",function(){"complete"===_.Da.readyState&&v.apply(this,arguments)}),_.Ca.attachEvent("onload",v))}}return p}};
_.Af=_.Af||{};_.C=_.zf.prototype;_.C.lk=(0,_.ba)("b");_.C.Hi=function(a,c){c({})};_.C.show=function(){this.d.Q().style.display="inline-block"};_.C.fj=function(){this.d.Q().style.display="none"};_.C.close=function(){this.d.close({})};_.C.enable=(0,_.w)();_.C.disable=(0,_.w)();


}catch(e){_._DumpException(e)}
try{
_.uq=(window.gapi||{}).load;

}catch(e){_._DumpException(e)}
try{
_.T.Af("bubble",function(a){(0,_.uq)("iframes-styles-bubble",a)});

}catch(e){_._DumpException(e)}
try{
_.T.Af("slide-menu",function(a){(0,_.uq)("iframes-styles-slide-menu",a)});

}catch(e){_._DumpException(e)}
try{
_.Np=function(a,c,f){return"string"==typeof a&&c[a.toLowerCase()]?a.toLowerCase():f};_.Op=function(a){var c=window.document.createElement("div"),f=window.document.createElement("a");f.href=a;c.appendChild(f);c.innerHTML=c.innerHTML;return c.firstChild.href};_.Pp=function(){return window.location.origin||window.location.protocol+"//"+window.location.host};
_.Qp=function(a,c,f,g){if(a)a=(0,_.Op)(a);else a:{a=(a=g)||"canonical";c=window.document.getElementsByTagName("link");f=0;for(g=c.length;f<g;f++){var h=c[f],k=h.getAttribute("rel");if(k&&k.toLowerCase()==a&&(h=h.getAttribute("href")))if(h=(0,_.Op)(h)){a=h;break a}}a=window.location.href}return a};_.Rp=function(a){a.source=[_.r,"source"];a.expandTo=[_.r,"expandTo"];a.align=[_.Sp];a.annotation=[_.Tp];a.origin=[_.Pp]};_.Up=function(a,c){if("string"==typeof a){var f;for(f=0;f<c.length;f++)if(c[f]==a.toLowerCase())return a.toLowerCase()}};
_.Sp=function(a){return(0,_.Up)(a,_.Vp)};_.Tp=function(a){return(0,_.Up)(a,_.Wp)};_.Xp=function(a){return"string"==typeof a?""!=a&&"0"!=a&&"false"!=a.toLowerCase():!!a};_.Yp=function(a){var c=(0,window.parseInt)(a,10);if(c==a)return(0,window.String)(c)};_.Zp=function(a){if((0,_.Xp)(a))return"true"};_.$p=function(a){return(0,_.Np)(a,_.aq,"standard")};_.bq=function(a,c){return"tall"==(0,_.$p)(c)?"true":a==_.r||(0,_.Xp)(a)?"true":"false"};
_.Vp=["left","right"];_.Wp="inline bubble none only pp vertical-bubble".split(" ");_.aq={tall:{"true":{width:50,height:60},"false":{width:50,height:24}},small:{"false":{width:24,height:15},"true":{width:70,height:15}},medium:{"false":{width:32,height:20},"true":{width:90,height:20}},standard:{"false":{width:38,height:24},"true":{width:106,height:24}}};
_.cq={href:[_.Qp,"url"],width:[_.Yp],size:[_.$p],resize:[_.Zp],autosize:[_.Zp],count:[function(a,c){return(0,_.bq)(c.count,c.size)}],db:[function(a,c,f){a==_.r&&f&&(a=f.db,a==_.r&&(a=f.gwidget&&f.gwidget.db));return(0,_.Xp)(a)?1:_.n}],ecp:[function(a,c,f){a==_.r&&f&&(a=f.ecp,a==_.r&&(a=f.gwidget&&f.gwidget.ecp));if((0,_.Xp)(a))return"true"}],textcolor:[function(a){if("string"==typeof a&&a.match(/^[0-9A-F]{6}$/i))return a}],drm:[_.Zp],recommendations:[],fu:[],ad:[_.Zp],cr:[_.Yp],ag:[_.Yp],"fr-ai":[], "fr-sigh":[]};


}catch(e){_._DumpException(e)}
try{
_.Yw=function(a,c,f){a=(0,_.Tp)(a);c=(0,_.$p)(c);if(""!=a){if("inline"==a||"only"==a)return a=450,f.width&&(a=120<f.width?f.width:120),{width:a,height:_.aq[c]["false"].height};if("bubble"!=a){if("none"==a)return _.aq[c]["false"];if("pp"==a)return _.Zw}}return _.aq[c]["true"]};_.Zw={width:180,height:35};
_.$w={"0":"plusone"};_.ax=(0,_.N)("iframes/plusone/preloadUrl");_.ax&&(_.$w[8]=_.ax);(0,_.Rp)(_.cq);_.$w[1]=_.cq;_.$w[2]={width:[function(a,c){return c.annotation?(0,_.Yw)(c.annotation,c.size,c).width:_.aq[(0,_.$p)(c.size)][(0,_.bq)(c.count,c.size)].width}],height:[function(a,c){return c.annotation?(0,_.Yw)(c.annotation,c.size,c).height:_.aq[(0,_.$p)(c.size)][(0,_.bq)(c.count,c.size)].height}]};_.$w[3]=["onPlusOne",function(a){return"on"==a.state?"+1":_.r}];_.$w[4]=["div","button"]; _.$w[6]=["onstartinteraction","onendinteraction","onpopup"];_.Na=_.Oa=_.Bf.cb(_.$w);
(0,_.O)("gapi.plusone.render",_.Oa.O);(0,_.O)("gapi.plusone.go",_.Oa.go);(0,_.O)("googleapisv0.plusone.render",_.Na.O);(0,_.O)("googleapisv0.plusone.go",_.Na.go);

}catch(e){_._DumpException(e)}
});

// Copyright 2002-2012 Google Inc.
