var ww,ww2,wh,scrollx,scrollxww,obiekty=[,,,{move:"ew",addclass:"anim",dist:-200,centeroffset:-1},{move:"ew",addclass:"anim05",dist:-100,centeroffset:-1},{move:"ns",dist:400,addclass:"anim",centeroffset:0.5},{move:"insta_revealb",addclass:"anim05",space:0.4},{move:"insta_revealb",addclass:"anim1",space:1},{opacity:!0,addclass:"anim"},,{move:"reveall",addclass:"anim05"},{move:"ns",dist:100,addclass:"anim",centeroffset:0.5},{move:"revealb",addclass:"anim05"},{move:"insta_revealb",addclass:"anim05",
space:0.5},{move:"sn",dist:100,addclass:"anim05",centeroffset:0.5},{move:"ns",dist:150,addclass:"anim05",centeroffset:0.5},,{opacity:!0},,,{move:"insta_revealb",addclass:"anim1",space:0.4},,{opacity:!0,centeroffset:0.2},,{move:"ns",dist:150,addclass:"anim05",centeroffset:0.1},{move:"ew",dist:-150},,{move:"ew",dist:-200,addclass:"anim1",centeroffset:-1},{move:"insta_rot",addclass:"anim2",space:0.6},,{opacity:!0,centeroffset:0.4,rightoffset:0.4,addclass:"anim2"},{move:"ns",dist:200,addclass:"anim",
centeroffset:0.5},{move:"ns",dist:-200,addclass:"anim",centeroffset:0.5},{move:"insta_revealb",dist:100,addclass:"anim1",space:0.7},{move:"insta_revealb",dist:100,addclass:"anim05",space:0.8},{move:"insta_revealb",dist:100,addclass:"anim05",space:0.7},{opacity:!0,centeroffset:0.2},{move:"ns",dist:-50,addclass:"anim",centeroffset:0.5},{move:"insta_reveall",dist:100,addclass:"anim15lin",space:0.7},{move:"ns",dist:50,addclass:"anim",centeroffset:0.5},{move:"ns",dist:-50,addclass:"anim",centeroffset:0.5},
{move:"ns",dist:50,addclass:"anim",centeroffset:0.5}];obiekty[46]={move:"insta_revealb",dist:100,addclass:"anim05",space:0.7};obiekty[47]={move:"ew",addclass:"anim05",dist:-100};obiekty[48]={move:"ew",addclass:"anim05",dist:100};obiekty[50]={move:"insta_zoom",addclass:"animbounce",space:0.7,dist:0.4};obiekty[51]={move:"insta_rot",addclass:"anim2",space:0.5};obiekty[52]={move:"ns",dist:-200,addclass:"anim",centeroffset:0.5};obiekty[53]={opacity:!0,centeroffset:0.2};
obiekty[54]={move:"insta_reveall",dist:100,addclass:"anim05",space:0.7};obiekty[55]={move:"insta_zoom",addclass:"animbounce",space:0.9,dist:0.7};obiekty[56]={move:"ns",dist:100,addclass:"anim",centeroffset:0.5};obiekty[57]={move:"insta_rot",addclass:"anim2",space:0.6};obiekty[77]={move:"ns",dist:300,centeroffset:0.2,rightoffset:0.2,opacity:!0,addclass:"anim"};obiekty[78]={move:"ns",dist:-100,centeroffset:0.2,rightoffset:0.2,opacity:!0,addclass:"anim"};obiekty[92]={move:"ns",opacity:!0,dist:500,addclass:"anim05"};
obiekty[93]={move:"insta_revealb",space:0.5,addclass:"anim05"};obiekty[120]={move:"ns",opacity:!0,dist:500,addclass:"anim05"};obiekty[121]={move:"insta_revealb",space:0.5,addclass:"anim05"};obiekty[123]={move:"ns",opacity:!0,dist:500,addclass:"anim05"};obiekty[124]={move:"insta_revealb",space:0.5,addclass:"anim05"};obiekty[155]={move:"ns",opacity:!0,dist:500,addclass:"anim05"};obiekty[156]={move:"insta_revealb",space:0.5,addclass:"anim05"};obiekty[203]={move:"ns",opacity:!0,dist:500,addclass:"anim05"};
obiekty[204]={move:"insta_revealb",space:0.5,addclass:"anim05"};obiekty[220]={move:"ns",opacity:!0,dist:500,addclass:"anim05"};obiekty[221]={move:"insta_revealb",space:0.5,addclass:"anim05"};obiekty[248]={move:"ns",opacity:!0,dist:500,addclass:"anim05"};obiekty[249]={move:"insta_revealb",space:0.5,addclass:"anim05"};obiekty[195]={move:"ns",dist:100,centeroffset:0,rightoffset:0.2};obiekty[68]={move:"insta_reveall",addclass:"anim1",space:0.5};obiekty[96]={move:"insta_revealb",addclass:"anim1",space:0.9};
obiekty[63]={move:"insta_reveall",addclass:"anim1",space:0.7};obiekty[64]={move:"insta_reveall",addclass:"anim05",space:0.5};obiekty[62]={move:"insta_reveall",addclass:"anim1",space:0.6};obiekty[74]={move:"insta_reveall",addclass:"anim05",space:0.7};obiekty[76]={move:"insta_reveall",addclass:"anim1",space:0.8};obiekty[72]={move:"insta_reveall",addclass:"anim05",space:0.9};obiekty[73]={move:"insta_reveall",addclass:"anim1",space:0.6};obiekty[75]={move:"insta_reveall",addclass:"anim05",space:0.5};
obiekty[65]={opacity:!0};obiekty[80]={move:"ns",dist:100,addclass:"anim05",centeroffset:0.3};obiekty[81]={move:"insta_revealb",addclass:"anim1",space:0.6};obiekty[83]={move:"ns",dist:100,addclass:"anim05",centeroffset:0.3};obiekty[84]={move:"insta_revealb",addclass:"anim1",space:0.6};obiekty[86]={move:"insta_revealb",addclass:"anim1",space:0.6};obiekty[88]={move:"insta_revealb",addclass:"anim1",space:0.6};obiekty[119]={move:"insta_zoom",addclass:"animbounce",space:0.1,dist:0.5};
obiekty[118]={move:"insta_zoom",addclass:"animbounce",space:0.1,dist:0.5};obiekty[114]={move:"insta_zoom",addclass:"animbounce",space:0.1,dist:0.5};obiekty[98]={move:"insta_revealb",addclass:"anim1",space:0.6};obiekty[109]={move:"insta_revealb",addclass:"anim1",space:0.2};obiekty[102]={move:"insta_revealb",addclass:"anim1",space:0.2};obiekty[103]={move:"insta_revealb",addclass:"anim1",space:0.2};obiekty[101]={move:"insta_reveall",addclass:"anim1",space:0.9};
obiekty[116]={move:"insta_revealb",addclass:"anim1",space:0.5};obiekty[110]={move:"insta_reveall",addclass:"anim2",space:0.2};obiekty[113]={move:"insta_reveall",addclass:"anim2",space:0.2};obiekty[105]={move:"ew",dist:100,addclass:"anim1",centeroffset:0.3};obiekty[100]={move:"ns",dist:-90,addclass:"anim",centeroffset:0};obiekty[115]={move:"ns",dist:300,addclass:"anim",rightoffset:0.5};obiekty[106]={move:"ns",dist:100,addclass:"anim",centeroffset:0.5};
obiekty[107]={move:"ns",dist:100,addclass:"anim",centeroffset:0.5};obiekty[108]={move:"ns",dist:100,addclass:"anim",centeroffset:0.5};obiekty[97]={move:"ew",dist:200,addclass:"anim1",centeroffset:-1};obiekty[143]={move:"insta_zoom",addclass:"animbounce",space:0.8,dist:0.5};obiekty[149]={move:"ns",dist:-100,addclass:"anim05",centeroffset:0.5};obiekty[150]={move:"ns",dist:100,addclass:"anim05",centeroffset:0.5};obiekty[145]={opacity:!0,move:"ns",dist:100,addclass:"anim05",centeroffset:0.5};
obiekty[146]={opacity:!0,move:"ns",dist:-100,addclass:"anim05",centeroffset:0.5};obiekty[148]={move:"ew",dist:-50,addclass:"anim1",centeroffset:0.5};obiekty[147]={move:"ew",dist:50,addclass:"anim1",centeroffset:0.5};obiekty[128]={move:"insta_revealb",addclass:"anim1",space:0.2};obiekty[139]={move:"insta_revealb",addclass:"anim2",space:0.4};obiekty[140]={move:"insta_reveall",addclass:"anim2",space:0.2};obiekty[132]={move:"ns",dist:20,addclass:"anim1",centeroffset:-0.5,rightoffset:0.5,opacity:!0};
obiekty[136]={move:"ns",dist:-20,addclass:"anim1",centeroffset:-0.5,rightoffset:0.5,opacity:!0};obiekty[138]={move:"ew",dist:20,addclass:"anim1",centeroffset:-0.5,rightoffset:0.5,opacity:!0};obiekty[135]={move:"ns",dist:-20,addclass:"anim1",centeroffset:-0.5,rightoffset:0.5,opacity:!0};obiekty[131]={move:"ns",dist:20,addclass:"anim1",centeroffset:-0.5,rightoffset:0.5,opacity:!0};obiekty[151]={move:"ew",dist:420,addclass:"anim",rightoffset:0.5,opacity:!0};
obiekty[152]={move:"ns",dist:220,addclass:"anim",rightoffset:0.5,opacity:!0};obiekty[126]={move:"ew",dist:200,addclass:"anim1",centeroffset:-1};obiekty[161]={move:"insta_revealb",addclass:"anim",space:0.4};obiekty[168]={move:"insta_reveall",addclass:"anim2",space:0.7};obiekty[169]={move:"insta_reveall",addclass:"anim2",space:0.7};obiekty[179]={move:"insta_reveall",addclass:"anim2",space:0.7};obiekty[171]={opacity:!0};obiekty[172]={opacity:!0,move:"ew",dist:-100,addclass:"anim"};obiekty[174]={opacity:!0};
obiekty[177]={move:"insta_rot",space:0.5,addclass:"anim2"};obiekty[170]={move:"ns",dist:60,addclass:"anim",centeroffset:-0.1,rightoffset:0.5};obiekty[165]={move:"ns",dist:-160,addclass:"anim",centeroffset:0.1};obiekty[173]={move:"ns",dist:80,addclass:"anim1",opacity:!0,centeroffset:-0.1,rightoffset:0.5};obiekty[175]={move:"ns",dist:60,addclass:"anim",centeroffset:-0.1,rightoffset:0.5};obiekty[176]={move:"ns",dist:70,addclass:"anim1",opacity:!0,centeroffset:0.2,rightoffset:0.5};
obiekty[162]={move:"ns",dist:70,addclass:"anim",centeroffset:-0.1,rightoffset:0.5};obiekty[154]={move:"ew",dist:500,addclass:"anim"};obiekty[188]={move:"insta_revealb",addclass:"anim1",space:0.4};obiekty[180]={move:"insta_revealb",addclass:"anim1",space:0.4};obiekty[194]={move:"insta_reveall",addclass:"anim",space:0.1};obiekty[181]={move:"insta_reveall",addclass:"anim2",space:0.1};obiekty[183]={move:"insta_revealb",addclass:"anim1",space:0.9};obiekty[207]={move:"ew",dist:-80,addclass:"anim",centeroffset:0.1};
obiekty[206]={move:"ew",dist:-80,addclass:"anim",centeroffset:0.1};obiekty[192]={move:"ns",dist:-380,addclass:"anim1",centeroffset:0.5};obiekty[191]={opacity:!0,move:"ns",dist:10,addclass:"animbounce",centeroffset:0.5};obiekty[196]={move:"ns",dist:-380,addclass:"anim1",centeroffset:0.5};obiekty[193]={move:"ns",dist:-380,addclass:"anim1",centeroffset:0.5};obiekty[197]={opacity:!0,move:"ns",dist:10,addclass:"animbounce",centeroffset:0.5};obiekty[202]={move:"ns",dist:-380,addclass:"anim1",centeroffset:0.5};
obiekty[201]={opacity:!0,move:"ns",dist:10,addclass:"animbounce",centeroffset:0.5};obiekty[199]={move:"ns",dist:-380,addclass:"anim1",centeroffset:0.5};obiekty[198]={move:"ns",dist:-380,addclass:"anim1",centeroffset:0.5};obiekty[200]={opacity:!0,move:"ns",dist:10,addclass:"animbounce",centeroffset:0.5};obiekty[179]={opacity:!0};obiekty[184]={opacity:!0};obiekty[185]={opacity:!0};obiekty[186]={opacity:!0};obiekty[187]={opacity:!0};obiekty[189]={opacity:!0};obiekty[178]={move:"ew",dist:300,opacity:!0};
obiekty[227]={opacity:!0};obiekty[225]={opacity:!0};obiekty[241]={opacity:!0};obiekty[211]={move:"ns",dist:340,addclass:"anim1",centeroffset:0.5};obiekty[214]={move:"ew",dist:80,addclass:"anim1",centeroffset:0.5};obiekty[223]={move:"ew",dist:-80,addclass:"anim1",centeroffset:0.5};obiekty[231]={move:"ew",dist:-180,addclass:"anim",centeroffset:0.5};obiekty[216]={move:"ns",dist:-100,addclass:"anim1",centeroffset:0.5};obiekty[219]={move:"ns",dist:-100,addclass:"anim1",centeroffset:0.5};
obiekty[217]={move:"ns",dist:-100,addclass:"anim1",centeroffset:0.5};obiekty[228]={move:"ns",dist:-100,addclass:"anim1",centeroffset:0.5};obiekty[224]={move:"ns",dist:100,addclass:"anim05",centeroffset:0.5};obiekty[238]={move:"insta_revealb",addclass:"anim1",space:0.4};obiekty[239]={move:"insta_revealb",addclass:"anim1",space:0.4};obiekty[240]={move:"insta_revealb",addclass:"anim1",space:0.4};obiekty[234]={move:"insta_revealb",addclass:"anim1",space:0.4};
obiekty[243]={move:"insta_revealb",addclass:"anim1",space:0.4};obiekty[244]={move:"insta_revealb",addclass:"anim1",space:0.4};obiekty[235]={move:"insta_revealb",addclass:"anim1",space:0.4};obiekty[236]={move:"insta_revealb",addclass:"anim1",space:0.4};obiekty[237]={move:"insta_revealb",addclass:"anim1",space:0.4};obiekty[232]={move:"insta_revealb",addclass:"anim1",space:0.4};obiekty[233]={move:"insta_revealb",addclass:"anim1",space:0.4};obiekty[209]={move:"insta_reveall",addclass:"anim1",space:0.9};
obiekty[212]={move:"insta_reveall",addclass:"anim2",space:0.1};obiekty[245]={move:"insta_reveall",addclass:"anim2",space:0.1};obiekty[256]={opacity:!0};obiekty[242]={opacity:!0,move:"ns",dist:300,rightoffset:-0.5,nolimits:!0};obiekty[255]={move:"insta_rot",space:0.5,addclass:"anim2"};obiekty[252]={move:"insta_zoom",addclass:"anim2",space:0.9,dist:1.3};obiekty[251]={opacity:!0,move:"ns",dist:-100,addclass:"anim1",centeroffset:0.5};obiekty[258]={move:"ns",dist:400,centeroffset:0.4,addclass:"anim05"};
obiekty[259]={move:"ns",dist:400,centeroffset:0.4,addclass:"anim05",opacity:!0};obiekty[268]={move:"ns",dist:400,centeroffset:0.4,addclass:"anim05"};obiekty[269]={move:"ns",dist:400,centeroffset:0.4,addclass:"anim05",opacity:!0};obiekty[261]={move:"ns",dist:400,centeroffset:0.4,addclass:"anim05",opacity:!0};obiekty[260]={move:"ns",dist:400,centeroffset:0.4,addclass:"anim05"};obiekty[266]={move:"ns",dist:400,centeroffset:0.4,addclass:"anim05"};
obiekty[267]={move:"ns",dist:400,centeroffset:0.4,addclass:"anim05",opacity:!0};obiekty[270]={move:"ns",dist:400,centeroffset:0.4,addclass:"anim05"};obiekty[271]={move:"ns",dist:400,centeroffset:0.4,addclass:"anim05",opacity:!0};obiekty[262]={move:"ns",dist:400,centeroffset:0.4,addclass:"anim05"};obiekty[263]={move:"ns",dist:400,centeroffset:0.4,addclass:"anim05",opacity:!0};obiekty[264]={move:"ns",dist:400,centeroffset:0.4,addclass:"anim05"};
obiekty[265]={move:"ns",dist:400,centeroffset:0.4,addclass:"anim05",opacity:!0};obiekty[247]={move:"ew",dist:580,addclass:"anim2",centeroffset:0.5};obiekty[274]={opacity:!0};obiekty[275]={move:"insta_revealb",addclass:"anim2",space:0.4};obiekty[276]={move:"insta_revealb",addclass:"anim2",space:0.4};
function obsetup(){for(var a in obiekty)obiekty[a].x=$("#il"+a).offset().left,obiekty[a].$ref=$("#il"+a+" div"),obiekty[a].w=$("#il"+a).width(),obiekty[a].h=$("#il"+a).height(),obiekty[a].$ref.width(obiekty[a].w),obiekty[a].$ref.height(obiekty[a].h),obiekty[a].centeroffset||(obiekty[a].centeroffset=0),obiekty[a].rightoffset||(obiekty[a].rightoffset=0),obiekty[a].dist||(obiekty[a].dist=200),obiekty[a].$ref.addClass(obiekty[a].addclass),obreset(a);$("#wrap").css("visibility","visible")}
function obreset(a){ob=obiekty[a];ob.opacity&&ob.$ref.css("opacity",0);switch(ob.move){case "ns":ob.$ref.css("top",-ob.dist);break;case "ew":ob.$ref.css("left",-ob.dist);break;case "insta_revealb":case "revealb":ob.$ref.css("height",0);break;case "reveall":case "insta_reveall":ob.$ref.css("width",0);break;case "insta_zoom":ob.$ref.removeClass(ob.addclass),ob.$ref.css("transform","scale("+ob.dist+")")}}function vis(a){ob=obiekty[a];return ob.x<scrollxww&&ob.x+ob.w>scrollx?!0:!1}
function kontroler(){for(var a in obiekty)if(ob=obiekty[a],vis(a))switch(pixdist=-(scrollx+ww/2-ob.x),dist=(pixdist-ww2*ob.centeroffset)/(ww2-ww2*ob.centeroffset),distrightmod=dist/((ww2-ww2*ob.centeroffset)/(ww2*ob.rightoffset)),dist+=distrightmod,ob.nolimits||(1<dist&&(dist=1),0>dist&&(dist=0)),ob.opacity&&ob.$ref.css("opacity",1-dist),ob.move){case "ns":ob.$ref.css("top",-dist*ob.dist);break;case "ew":ob.$ref.css("left",-dist*ob.dist);break;case "reveall":ob.$ref.css("width",(1-dist)*ob.w);break;
case "revealb":ob.$ref.css("height",(1-dist)*ob.h);break;case "insta_revealb":dist<ob.space&&ob.$ref.css("height",ob.h);break;case "insta_reveall":dist<ob.space&&ob.$ref.css("width",ob.w);break;case "insta_rot":!ob.busy&&dist<ob.space&&(ob.$ref.addClass(ob.addclass),ob.$ref.css("transform","rotate(360deg)"),ob.busy=!0);break;case "insta_zoom":!ob.busy&&dist<ob.space&&(ob.$ref.addClass(ob.addclass),ob.$ref.css("transform","scale(1)"),ob.busy=!0)}else switch(ob.move){case "insta_rot":ob.busy&&(ob.$ref.removeClass(ob.addclass),
ob.$ref.css("transform","rotate(0deg)"),ob.busy=!1);break;case "insta_zoom":ob.busy&&(obreset(a),ob.busy=!1);break;case "insta_revealb":case "insta_reveall":obreset(a)}}
function resizer(){ww=$(window).width();ww2=Math.round(ww/2);wh=$(window).height();$("#wrap").css("top",(wh-700)/2).css("left",ww);$("#prewrap, #postwrap").css("width",ww);$("#postwrap").css("left",ww+$("#wrap").width());isiPhone()||$(".separ, .fullh").css("height",wh).css("marginTop",-(wh-700)/2);$("#prewrap .in").width(ww-60).height(wh-60);$("#postwrap .in").height(wh);$("#postwrap").show()}
function navctl(){0==scrollx?$("#navl").fadeOut():$("#navl").fadeIn();scrollxww>=$(document).width()?$("#navr").fadeOut():$("#navr").fadeIn()}function isiPhone(){return navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)?!0:!1}
$(document).ready(function(){isiPhone()&&$("#navl, #navr").remove();$(window).resize(function(){resizer()});resizer();obsetup();$(window).load(function(){obsetup();$(window).scroll()});$(window).scroll(function(){scrollx=$(window).scrollLeft();scrollxww=scrollx+ww;kontroler();navctl()});$(window).scroll();setTimeout(function(){$(window).resize()},500);$("#navr").click(function(){ww=$(window).width();$("html, body").stop(!0,!0).animate({scrollLeft:"+="+0.5*ww},800,function(){navctl()})});$("#navl").click(function(){ww=
$(window).width();$("html, body").stop(!0,!0).animate({scrollLeft:"-="+0.5*ww},800,function(){navctl()})});$(document).keydown(function(a){if(39==a.keyCode||32==a.keyCode||40==a.keyCode)$("html, body").stop(!0,!0).animate({scrollLeft:"+="+0.5*ww},800,function(){navctl()}),a.preventDefault?a.preventDefault():a.returnValue=!1;if(37==a.keyCode||38==a.keyCode)$("html, body").stop(!0,!0).animate({scrollLeft:"-="+0.5*ww},800,function(){navctl()}),a.preventDefault?a.preventDefault():a.returnValue=!1})});